// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: veyron_wpp_bot/protos/listener.proto

package listener_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_veyron_wpp_bot_protos_listener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veyron_wpp_bot_protos_listener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_veyron_wpp_bot_protos_listener_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_veyron_wpp_bot_protos_listener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veyron_wpp_bot_protos_listener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_veyron_wpp_bot_protos_listener_proto_rawDescGZIP(), []int{1}
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_veyron_wpp_bot_protos_listener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veyron_wpp_bot_protos_listener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_veyron_wpp_bot_protos_listener_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_veyron_wpp_bot_protos_listener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veyron_wpp_bot_protos_listener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_veyron_wpp_bot_protos_listener_proto_rawDescGZIP(), []int{3}
}

var File_veyron_wpp_bot_protos_listener_proto protoreflect.FileDescriptor

const file_veyron_wpp_bot_protos_listener_proto_rawDesc = "" +
	"\n" +
	"$veyron_wpp_bot/protos/listener.proto\x12\x0elistener_proto\"/\n" +
	"\n" +
	"AddRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"\r\n" +
	"\vAddResponse\"2\n" +
	"\rRemoveRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\"\x10\n" +
	"\x0eRemoveResponse2\xba\x01\n" +
	"\x0fListenerService\x12M\n" +
	"\x12AddPhoneToListener\x12\x1a.listener_proto.AddRequest\x1a\x1b.listener_proto.AddResponse\x12X\n" +
	"\x17RemovePhoneFromListener\x12\x1d.listener_proto.RemoveRequest\x1a\x1e.listener_proto.RemoveResponseB#Z!./generated_protos/listener_protob\x06proto3"

var (
	file_veyron_wpp_bot_protos_listener_proto_rawDescOnce sync.Once
	file_veyron_wpp_bot_protos_listener_proto_rawDescData []byte
)

func file_veyron_wpp_bot_protos_listener_proto_rawDescGZIP() []byte {
	file_veyron_wpp_bot_protos_listener_proto_rawDescOnce.Do(func() {
		file_veyron_wpp_bot_protos_listener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veyron_wpp_bot_protos_listener_proto_rawDesc), len(file_veyron_wpp_bot_protos_listener_proto_rawDesc)))
	})
	return file_veyron_wpp_bot_protos_listener_proto_rawDescData
}

var file_veyron_wpp_bot_protos_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_veyron_wpp_bot_protos_listener_proto_goTypes = []any{
	(*AddRequest)(nil),     // 0: listener_proto.AddRequest
	(*AddResponse)(nil),    // 1: listener_proto.AddResponse
	(*RemoveRequest)(nil),  // 2: listener_proto.RemoveRequest
	(*RemoveResponse)(nil), // 3: listener_proto.RemoveResponse
}
var file_veyron_wpp_bot_protos_listener_proto_depIdxs = []int32{
	0, // 0: listener_proto.ListenerService.AddPhoneToListener:input_type -> listener_proto.AddRequest
	2, // 1: listener_proto.ListenerService.RemovePhoneFromListener:input_type -> listener_proto.RemoveRequest
	1, // 2: listener_proto.ListenerService.AddPhoneToListener:output_type -> listener_proto.AddResponse
	3, // 3: listener_proto.ListenerService.RemovePhoneFromListener:output_type -> listener_proto.RemoveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_veyron_wpp_bot_protos_listener_proto_init() }
func file_veyron_wpp_bot_protos_listener_proto_init() {
	if File_veyron_wpp_bot_protos_listener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veyron_wpp_bot_protos_listener_proto_rawDesc), len(file_veyron_wpp_bot_protos_listener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_veyron_wpp_bot_protos_listener_proto_goTypes,
		DependencyIndexes: file_veyron_wpp_bot_protos_listener_proto_depIdxs,
		MessageInfos:      file_veyron_wpp_bot_protos_listener_proto_msgTypes,
	}.Build()
	File_veyron_wpp_bot_protos_listener_proto = out.File
	file_veyron_wpp_bot_protos_listener_proto_goTypes = nil
	file_veyron_wpp_bot_protos_listener_proto_depIdxs = nil
}
