// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: transaction-service/protos/account_balance.proto

package account_balance_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	CreatedBy     uint32                 `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     uint32                 `protobuf:"varint,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy     *uint32                `protobuf:"varint,8,opt,name=deleted_by,json=deletedBy,proto3,oneof" json:"deleted_by,omitempty"`
	AccountId     uint32                 `protobuf:"varint,9,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CurrencyId    uint32                 `protobuf:"varint,10,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,11,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBalance) Reset() {
	*x = AccountBalance{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalance) ProtoMessage() {}

func (x *AccountBalance) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalance.ProtoReflect.Descriptor instead.
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{0}
}

func (x *AccountBalance) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountBalance) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *AccountBalance) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AccountBalance) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AccountBalance) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *AccountBalance) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *AccountBalance) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *AccountBalance) GetDeletedBy() uint32 {
	if x != nil && x.DeletedBy != nil {
		return *x.DeletedBy
	}
	return 0
}

func (x *AccountBalance) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountBalance) GetCurrencyId() uint32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *AccountBalance) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	AccountId     uint32                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CurrencyId    uint32                 `protobuf:"varint,3,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountBalanceRequest) Reset() {
	*x = CreateAccountBalanceRequest{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountBalanceRequest) ProtoMessage() {}

func (x *CreateAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountBalanceRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateAccountBalanceRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateAccountBalanceRequest) GetCurrencyId() uint32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *CreateAccountBalanceRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateAccountBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CurrencyId    uint32                 `protobuf:"varint,2,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedBy     uint32                 `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     uint32                 `protobuf:"varint,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy     uint32                 `protobuf:"varint,9,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountBalanceResponse) Reset() {
	*x = CreateAccountBalanceResponse{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountBalanceResponse) ProtoMessage() {}

func (x *CreateAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountBalanceResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateAccountBalanceResponse) GetCurrencyId() uint32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *CreateAccountBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateAccountBalanceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateAccountBalanceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateAccountBalanceResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *CreateAccountBalanceResponse) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *CreateAccountBalanceResponse) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *CreateAccountBalanceResponse) GetDeletedBy() uint32 {
	if x != nil {
		return x.DeletedBy
	}
	return 0
}

type GetAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountBalanceRequest) Reset() {
	*x = GetAccountBalanceRequest{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceRequest) ProtoMessage() {}

func (x *GetAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountBalanceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAccountBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	AccountId     uint32                 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CurrencyId    uint32                 `protobuf:"varint,4,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedBy     uint32                 `protobuf:"varint,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     uint32                 `protobuf:"varint,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy     uint32                 `protobuf:"varint,11,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountBalanceResponse) Reset() {
	*x = GetAccountBalanceResponse{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceResponse) ProtoMessage() {}

func (x *GetAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountBalanceResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetCurrencyId() uint32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetAccountBalanceResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetAccountBalanceResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *GetAccountBalanceResponse) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *GetAccountBalanceResponse) GetDeletedBy() uint32 {
	if x != nil {
		return x.DeletedBy
	}
	return 0
}

type ListAccountBalanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          *uint32                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset         *uint32                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	IncludeDeleted *bool                  `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	AccountId      *uint32                `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	Balance        *bool                  `protobuf:"varint,5,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
	CurrencyId     *uint32                `protobuf:"varint,6,opt,name=currency_id,json=currencyId,proto3,oneof" json:"currency_id,omitempty"`
	Orderby        *OrderBy               `protobuf:"bytes,7,opt,name=orderby,proto3,oneof" json:"orderby,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAccountBalanceRequest) Reset() {
	*x = ListAccountBalanceRequest{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountBalanceRequest) ProtoMessage() {}

func (x *ListAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*ListAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccountBalanceRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListAccountBalanceRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListAccountBalanceRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

func (x *ListAccountBalanceRequest) GetAccountId() uint32 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *ListAccountBalanceRequest) GetBalance() bool {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return false
}

func (x *ListAccountBalanceRequest) GetCurrencyId() uint32 {
	if x != nil && x.CurrencyId != nil {
		return *x.CurrencyId
	}
	return 0
}

func (x *ListAccountBalanceRequest) GetOrderby() *OrderBy {
	if x != nil {
		return x.Orderby
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{6}
}

func (x *OrderBy) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *OrderBy) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

type ListAccountBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Rows          []*AccountBalance      `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountBalanceResponse) Reset() {
	*x = ListAccountBalanceResponse{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountBalanceResponse) ProtoMessage() {}

func (x *ListAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*ListAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{7}
}

func (x *ListAccountBalanceResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListAccountBalanceResponse) GetRows() []*AccountBalance {
	if x != nil {
		return x.Rows
	}
	return nil
}

type UpdateAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	AccountId     *uint32                `protobuf:"varint,4,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	CurrencyId    *uint32                `protobuf:"varint,5,opt,name=currency_id,json=currencyId,proto3,oneof" json:"currency_id,omitempty"`
	Balance       *float64               `protobuf:"fixed64,6,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountBalanceRequest) Reset() {
	*x = UpdateAccountBalanceRequest{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountBalanceRequest) ProtoMessage() {}

func (x *UpdateAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAccountBalanceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAccountBalanceRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *UpdateAccountBalanceRequest) GetAccountId() uint32 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *UpdateAccountBalanceRequest) GetCurrencyId() uint32 {
	if x != nil && x.CurrencyId != nil {
		return *x.CurrencyId
	}
	return 0
}

func (x *UpdateAccountBalanceRequest) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

type UpdateAccountBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	AccountId     uint32                 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CurrencyId    uint32                 `protobuf:"varint,4,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountBalanceResponse) Reset() {
	*x = UpdateAccountBalanceResponse{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountBalanceResponse) ProtoMessage() {}

func (x *UpdateAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAccountBalanceResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAccountBalanceResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *UpdateAccountBalanceResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateAccountBalanceResponse) GetCurrencyId() uint32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *UpdateAccountBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type DeleteAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountBalanceRequest) Reset() {
	*x = DeleteAccountBalanceRequest{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountBalanceRequest) ProtoMessage() {}

func (x *DeleteAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAccountBalanceRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteAccountBalanceRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type DeleteAccountBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountBalanceResponse) Reset() {
	*x = DeleteAccountBalanceResponse{}
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountBalanceResponse) ProtoMessage() {}

func (x *DeleteAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_account_balance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_account_balance_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAccountBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transaction_service_protos_account_balance_proto protoreflect.FileDescriptor

const file_transaction_service_protos_account_balance_proto_rawDesc = "" +
	"\n" +
	"0transaction-service/protos/account_balance.proto\x12\x15account_balance_proto\"\xff\x02\n" +
	"\x0eAccountBalance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\tH\x00R\tdeletedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\rR\tupdatedBy\x12\"\n" +
	"\n" +
	"deleted_by\x18\b \x01(\rH\x01R\tdeletedBy\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"account_id\x18\t \x01(\rR\taccountId\x12\x1f\n" +
	"\vcurrency_id\x18\n" +
	" \x01(\rR\n" +
	"currencyId\x12\x18\n" +
	"\abalance\x18\v \x01(\x01R\abalanceB\r\n" +
	"\v_deleted_atB\r\n" +
	"\v_deleted_by\"\x9a\x01\n" +
	"\x1bCreateAccountBalanceRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\rR\taccountId\x12\x1f\n" +
	"\vcurrency_id\x18\x03 \x01(\rR\n" +
	"currencyId\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\"\xb2\x02\n" +
	"\x1cCreateAccountBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x1f\n" +
	"\vcurrency_id\x18\x02 \x01(\rR\n" +
	"currencyId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\tR\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\rR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\t \x01(\rR\tdeletedBy\"*\n" +
	"\x18GetAccountBalanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xe2\x02\n" +
	"\x19GetAccountBalanceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\rR\taccountId\x12\x1f\n" +
	"\vcurrency_id\x18\x04 \x01(\rR\n" +
	"currencyId\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x01R\abalance\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\b \x01(\tR\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\rR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\v \x01(\rR\tdeletedBy\"\x89\x03\n" +
	"\x19ListAccountBalanceRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\rH\x01R\x06offset\x88\x01\x01\x12,\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bH\x02R\x0eincludeDeleted\x88\x01\x01\x12\"\n" +
	"\n" +
	"account_id\x18\x04 \x01(\rH\x03R\taccountId\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x05 \x01(\bH\x04R\abalance\x88\x01\x01\x12$\n" +
	"\vcurrency_id\x18\x06 \x01(\rH\x05R\n" +
	"currencyId\x88\x01\x01\x12=\n" +
	"\aorderby\x18\a \x01(\v2\x1e.account_balance_proto.OrderByH\x06R\aorderby\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x12\n" +
	"\x10_include_deletedB\r\n" +
	"\v_account_idB\n" +
	"\n" +
	"\b_balanceB\x0e\n" +
	"\f_currency_idB\n" +
	"\n" +
	"\b_orderby\"X\n" +
	"\aOrderBy\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tH\x01R\tcreatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_at\"m\n" +
	"\x1aListAccountBalanceResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x129\n" +
	"\x04rows\x18\x02 \x03(\v2%.account_balance_proto.AccountBalanceR\x04rows\"\xe4\x01\n" +
	"\x1bUpdateAccountBalanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\x12\"\n" +
	"\n" +
	"account_id\x18\x04 \x01(\rH\x00R\taccountId\x88\x01\x01\x12$\n" +
	"\vcurrency_id\x18\x05 \x01(\rH\x01R\n" +
	"currencyId\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x06 \x01(\x01H\x02R\abalance\x88\x01\x01B\r\n" +
	"\v_account_idB\x0e\n" +
	"\f_currency_idB\n" +
	"\n" +
	"\b_balance\"\xab\x01\n" +
	"\x1cUpdateAccountBalanceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\rR\taccountId\x12\x1f\n" +
	"\vcurrency_id\x18\x04 \x01(\rR\n" +
	"currencyId\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x01R\abalance\"P\n" +
	"\x1bDeleteAccountBalanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\"8\n" +
	"\x1cDeleteAccountBalanceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc7\x04\n" +
	"\x15AccountBalanceService\x12q\n" +
	"\x06Create\x122.account_balance_proto.CreateAccountBalanceRequest\x1a3.account_balance_proto.CreateAccountBalanceResponse\x12h\n" +
	"\x03Get\x12/.account_balance_proto.GetAccountBalanceRequest\x1a0.account_balance_proto.GetAccountBalanceResponse\x12q\n" +
	"\x06Update\x122.account_balance_proto.UpdateAccountBalanceRequest\x1a3.account_balance_proto.UpdateAccountBalanceResponse\x12q\n" +
	"\x06Delete\x122.account_balance_proto.DeleteAccountBalanceRequest\x1a3.account_balance_proto.DeleteAccountBalanceResponse\x12k\n" +
	"\x04List\x120.account_balance_proto.ListAccountBalanceRequest\x1a1.account_balance_proto.ListAccountBalanceResponseB*Z(./generated_protos/account_balance_protob\x06proto3"

var (
	file_transaction_service_protos_account_balance_proto_rawDescOnce sync.Once
	file_transaction_service_protos_account_balance_proto_rawDescData []byte
)

func file_transaction_service_protos_account_balance_proto_rawDescGZIP() []byte {
	file_transaction_service_protos_account_balance_proto_rawDescOnce.Do(func() {
		file_transaction_service_protos_account_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_service_protos_account_balance_proto_rawDesc), len(file_transaction_service_protos_account_balance_proto_rawDesc)))
	})
	return file_transaction_service_protos_account_balance_proto_rawDescData
}

var file_transaction_service_protos_account_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transaction_service_protos_account_balance_proto_goTypes = []any{
	(*AccountBalance)(nil),               // 0: account_balance_proto.AccountBalance
	(*CreateAccountBalanceRequest)(nil),  // 1: account_balance_proto.CreateAccountBalanceRequest
	(*CreateAccountBalanceResponse)(nil), // 2: account_balance_proto.CreateAccountBalanceResponse
	(*GetAccountBalanceRequest)(nil),     // 3: account_balance_proto.GetAccountBalanceRequest
	(*GetAccountBalanceResponse)(nil),    // 4: account_balance_proto.GetAccountBalanceResponse
	(*ListAccountBalanceRequest)(nil),    // 5: account_balance_proto.ListAccountBalanceRequest
	(*OrderBy)(nil),                      // 6: account_balance_proto.OrderBy
	(*ListAccountBalanceResponse)(nil),   // 7: account_balance_proto.ListAccountBalanceResponse
	(*UpdateAccountBalanceRequest)(nil),  // 8: account_balance_proto.UpdateAccountBalanceRequest
	(*UpdateAccountBalanceResponse)(nil), // 9: account_balance_proto.UpdateAccountBalanceResponse
	(*DeleteAccountBalanceRequest)(nil),  // 10: account_balance_proto.DeleteAccountBalanceRequest
	(*DeleteAccountBalanceResponse)(nil), // 11: account_balance_proto.DeleteAccountBalanceResponse
}
var file_transaction_service_protos_account_balance_proto_depIdxs = []int32{
	6,  // 0: account_balance_proto.ListAccountBalanceRequest.orderby:type_name -> account_balance_proto.OrderBy
	0,  // 1: account_balance_proto.ListAccountBalanceResponse.rows:type_name -> account_balance_proto.AccountBalance
	1,  // 2: account_balance_proto.AccountBalanceService.Create:input_type -> account_balance_proto.CreateAccountBalanceRequest
	3,  // 3: account_balance_proto.AccountBalanceService.Get:input_type -> account_balance_proto.GetAccountBalanceRequest
	8,  // 4: account_balance_proto.AccountBalanceService.Update:input_type -> account_balance_proto.UpdateAccountBalanceRequest
	10, // 5: account_balance_proto.AccountBalanceService.Delete:input_type -> account_balance_proto.DeleteAccountBalanceRequest
	5,  // 6: account_balance_proto.AccountBalanceService.List:input_type -> account_balance_proto.ListAccountBalanceRequest
	2,  // 7: account_balance_proto.AccountBalanceService.Create:output_type -> account_balance_proto.CreateAccountBalanceResponse
	4,  // 8: account_balance_proto.AccountBalanceService.Get:output_type -> account_balance_proto.GetAccountBalanceResponse
	9,  // 9: account_balance_proto.AccountBalanceService.Update:output_type -> account_balance_proto.UpdateAccountBalanceResponse
	11, // 10: account_balance_proto.AccountBalanceService.Delete:output_type -> account_balance_proto.DeleteAccountBalanceResponse
	7,  // 11: account_balance_proto.AccountBalanceService.List:output_type -> account_balance_proto.ListAccountBalanceResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_service_protos_account_balance_proto_init() }
func file_transaction_service_protos_account_balance_proto_init() {
	if File_transaction_service_protos_account_balance_proto != nil {
		return
	}
	file_transaction_service_protos_account_balance_proto_msgTypes[0].OneofWrappers = []any{}
	file_transaction_service_protos_account_balance_proto_msgTypes[5].OneofWrappers = []any{}
	file_transaction_service_protos_account_balance_proto_msgTypes[6].OneofWrappers = []any{}
	file_transaction_service_protos_account_balance_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_service_protos_account_balance_proto_rawDesc), len(file_transaction_service_protos_account_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_service_protos_account_balance_proto_goTypes,
		DependencyIndexes: file_transaction_service_protos_account_balance_proto_depIdxs,
		MessageInfos:      file_transaction_service_protos_account_balance_proto_msgTypes,
	}.Build()
	File_transaction_service_protos_account_balance_proto = out.File
	file_transaction_service_protos_account_balance_proto_goTypes = nil
	file_transaction_service_protos_account_balance_proto_depIdxs = nil
}
