syntax = "proto3";

package contact_proto;

option go_package = "./generated_protos/contact_proto";

service ContactService {
    // Contact CRUD
    rpc Create (CreateRequest) returns (CreateResponse) {};
    rpc Get (GetRequest) returns (GetResponse) {};
    rpc Update (UpdateRequest) returns (UpdateResponse) {};
    rpc Delete (DeleteRequest) returns (DeleteResponse) {};
    rpc List (ListRequest) returns (ListResponse) {};
}

message ContactDto {
    int32 id = 1;
    string name = 2;
    string chat_id = 3;
    string client_id = 4;
    string phone_number = 5;
    int32 whatsapp_config_id = 6;
}

message CreateRequest {
    string name = 1;
    string chat_id = 2;
    string client_id = 3;
    string phone_number = 4;
    int32 whatsapp_config_id = 5;
}

message CreateResponse {
    string name = 1;
    string chat_id = 2;
    string client_id = 3;
    string phone_number = 4;
    int32 whatsapp_config_id = 5;
}

message GetRequest {
    int32 id = 1;
}

message GetResponse {
    int32 id = 1;
    string name = 2;
    string chat_id = 3;
    string client_id = 4;
    string phone_number = 5;
    int32 whatsapp_config_id = 6;
}

message UpdateRequest {
    int32 id = 1;
    optional string name = 2;
    optional string chat_id = 3;
    optional string client_id = 4;
    optional string phone_number = 5;
    optional int32 whatsapp_config_id = 6;
}

message UpdateResponse {
    int32 id = 1;
    string name = 2;
    string chat_id = 3;
    string client_id = 4;
    string phone_number = 5;
    int32 whatsapp_config_id = 6;
}

message DeleteRequest {
    int32 id = 1;
}

message DeleteResponse {}

message ListRequest {
    optional int32 limit = 1;
    optional int32 offset = 2;
    optional int32 chat_id = 3;
}

message ListResponse {
    repeated ContactDto rows = 1;
    int32 count = 2;
}