syntax = "proto3";

package message_template_proto;

option go_package = "./generated_protos/message_template_proto";

service MessageTemplateService {
    // MessageTemplate CRUD
    rpc Create (CreateRequest) returns (CreateResponse) {}
    rpc Get    (GetRequest)    returns (GetResponse) {}
    rpc Update (UpdateRequest) returns (UpdateResponse) {}
    rpc Delete (DeleteRequest) returns (DeleteResponse) {}
    rpc List   (ListRequest)   returns (ListResponse) {}
}

message MessageTemplateDto {
    uint32  id      = 1;
    string message = 2;
}

message CreateRequest {
    string message = 1;
}

message CreateResponse {
    uint32  id      = 1;
    string message = 2;
}

message GetRequest {
    uint32 id = 1;
}

message GetResponse {
    uint32  id      = 1;
    string message = 2;
}

message UpdateRequest {
    uint32 id = 1;
    optional string message = 2;
}

message UpdateResponse {
    uint32  id      = 1;
    string message = 2;
}

message DeleteRequest {
    uint32 id = 1;
}

message DeleteResponse {}

message ListRequest {
    optional int32 limit  = 1;
    optional int32 offset = 2;
}

message ListResponse {
    repeated MessageTemplateDto rows = 1;
    int32 count = 2;
}