syntax = "proto3";

package auth_users_proto;

option go_package = "./generated_protos/auth_users_proto";

service AuthUsersService {
  rpc Create (CreateRequest) returns (CreateResponse);
  rpc Get (GetRequest) returns (GetResponse);
  rpc List (ListRequest) returns (ListResponse);
  rpc Update (UpdateRequest) returns (UpdateResponse);
  rpc Delete (DeleteRequest) returns (DeleteResponse);
  rpc UpdateEmail(UpdateEmailRequest) returns (UpdateEmailResponse);
  rpc UpdatePhone(UpdatePhoneRequest) returns (UpdatePhoneResponse);

  rpc VerifyPassword (VerifyPasswordRequest) returns (VerifyPasswordResponse);
}

message Phone {
  uint32 id = 1;
  string phone = 2;
  string created_at = 3;
  optional string deleted_at = 4;
  bool main = 5;
  uint32 user_id = 6;
}

message Email {
  uint32 id = 1;
  string email = 2;
  string created_at = 3;
  optional string deleted_at = 4;
  bool main = 5;
  uint32 user_id = 6;
}

message User {
  uint32 id = 1;
  string name = 2;
  string surname = 3;
  repeated Email emails = 4;
  string created_at = 5;
  optional string deleted_at = 6;
  repeated Phone phones = 7;
}

message Relations {
  bool emails = 1;
  bool phones = 2;
  bool passwords = 3;
  bool roles = 4;
}

message Password {
  uint32 id = 1;
  string password = 2;
  string created_at = 3;
  optional string deleted_at = 4;
  uint32 user_id = 5;
}

message CreateRequest {
  string name = 1;
  string surname = 2;
  string email = 3;
  string password = 4;
  string confirm_password = 5;
  string phone = 6;
}

message CreateResponse {
  User user = 1;
}

message GetRequest {
  uint32 id = 1;
}

message GetResponse {
  User user = 1;
}

message ListRequest {
  optional uint32 id = 1;
  optional string email = 2;
  optional string name = 3;
  optional string surname = 4;
  optional uint32 limit = 5;
  optional uint32 offset = 6;
  optional bool include_deleted = 7;
  optional string phone = 8;
  optional Relations relations = 9;
}

message ListResponse {
  uint32 count = 1;
  repeated User rows = 2;
}

message UpdateRequest {
  optional uint32 id = 1;
  optional string name = 2;
  optional string surname = 3;
  optional string email = 4;
  optional string password = 5;
  optional string confirm_password = 6;
  optional string phone = 7;
}

// teste

message UpdateResponse {
  User user = 1;
}

message DeleteRequest {
  uint32 id = 1;
}

message DeleteResponse {}

message VerifyPasswordRequest {
  optional uint32 id = 1;
  string password = 2;
  optional string email = 3;
  optional string phone = 4;
}

message VerifyPasswordResponse {
  bool success = 5;
  optional uint32 remaining_retries = 6;
  optional string suspended_until = 7;
  optional User user = 8;
}

message UpdateEmailRequest {
  int32 user_id = 1;
  string email = 2;
}

message UpdateEmailResponse {
  User user = 1;
}

message UpdatePhoneRequest {
  int32 user_id = 1;
  string phone = 2;
}

message UpdatePhoneResponse {
  User user = 1;
}