syntax = "proto3";

package ban_proto;

option go_package = "./generated_protos/ban_proto";

service BanService {
    rpc Create (CreateRequest) returns (CreateResponse);
    rpc Delete (DeleteRequest) returns (DeleteResponse);
    rpc List (ListRequest) returns (ListResponse);
    rpc Update (UpdateRequest) returns (UpdateResponse);
    rpc Get (GetRequest) returns (GetResponse);
}


message Ban {
    uint32 id = 1;
    string created_at = 2;
    optional string deleted_at = 3;
    uint32 user_id = 4;
    string expires_at = 5;
}

message CreateRequest {
    uint32 user_id = 1;
    string expires_at = 2;
}

message CreateResponse {
    uint32 user_id = 1;
    string expires_at = 2;
}

message DeleteRequest {
    uint32 id = 1;
}

message DeleteResponse {}

message GetRequest {
    uint32 id = 1;
    uint32 limit = 2;
    uint32 offset = 3;
}

message GetResponse {
    uint32 user_id = 4;
    string expires_at = 5;
}

message ListRequest {
    optional uint32 limit = 6;
    optional uint32 offset = 7;
    optional bool include_deleted = 8;
    optional OrderBy order_by = 9;
    optional uint32 user_id = 10;
    optional string expires_at = 11;
}

message OrderBy {
    optional string id = 12;
    optional string created_at = 13;
}

message ListResponse {
    repeated Ban rows = 14;
    uint32 count = 15;
}

message UpdateRequest {
    uint32 id = 16;
    optional uint32 user_id = 17;
    optional string expires_at = 18;
}

message UpdateResponse {
    uint32 user_id = 19;
    string expires_at = 20;
}