syntax = "proto3";

package first_login_proto;

option go_package = "./generated_protos/first_login_proto";

service FirstLoginService {
    rpc Create (CreateRequest) returns (CreateResponse);
    rpc Delete (DeleteRequest) returns (DeleteResponse);
    rpc List (ListRequest) returns (ListResponse);
    rpc Update (UpdateRequest) returns (UpdateResponse);
    rpc Get (GetRequest) returns (GetResponse);
}

message FirstLogin {
    uint32 id = 1;
    string created_at = 2;
    optional string deleted_at = 3;
    int32 user_id = 4;
    bool successful = 5;
}

message CreateRequest {
    int32 user_id = 1;
    bool successful = 2;
}

message CreateResponse {
    int32 user_id = 1;
    bool successful = 2;
}

message DeleteRequest {
    uint32 id = 1;
}

message DeleteResponse {}

message GetRequest {
    uint32 id = 1;
    uint32 limit = 2;
    uint32 offset = 3;
}

message GetResponse {
    int32 user_id = 4;
    bool successful = 5;
}


message ListRequest {
    optional uint32 limit = 6;
    optional uint32 offset = 7;
    optional bool include_deleted = 8;
    optional OrderBy order_by = 9;
    optional int32 user_id = 10;
    optional bool successful = 11;
}

message OrderBy {
    optional string id = 12;
    optional string created_at = 13;
}

message ListResponse {
    repeated FirstLogin rows = 14;
    uint32 count = 15;
}

message UpdateRequest {
    uint32 id = 16;
    optional int32 user_id = 17;
    optional bool successful = 18;
}

message UpdateResponse {
    int32 user_id = 19;
    bool successful = 20;
}