syntax = "proto3";

package images_proto;

option go_package = "./generated_protos/images_proto";

service ImagesService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc List(ListRequest) returns (ListResponse);
}

message Images {
  uint32 id = 1;
  string created_at = 2;
  optional string deleted_at = 3;
  uint32 image_folder_path_id = 4;
  string content = 5;
  string path = 6;
}

message CreateRequest {
  uint32 image_folder_path_id = 1;
  string content = 2;
  string path = 3;
  
}

message CreateResponse {
  Images images = 1;
}

message GetRequest {
  uint32 id = 1;
}

message GetResponse {
  Images images = 1;
}

message UpdateRequest {
  uint32 id = 1;
  optional uint32 image_folder_path_id = 2;
  optional string content = 3;
  optional string path = 4;
}

message UpdateResponse {
  Images images = 1;
}

message DeleteRequest {
  uint32 id = 1;
}

message DeleteResponse {}

message ListRequest {
  optional uint32 limit = 1;
  optional uint32 offset = 2;
  optional uint32 image_folder_path_id = 3;
  optional string content = 4;
  optional string path = 5;
  optional bool include_deleted = 6;
  optional OrderBy orderby = 7;
}

message OrderBy {
  optional string id = 1;
  optional string created_at = 2;
}

message ListResponse {
  repeated Images rows = 1;
  uint32 count = 2;
}
