syntax = "proto3";

package promotions_proto;

option go_package = "./generated_protos/promotions_proto";

service PromotionsService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc AddProductsToPromotion(AddProductsToPromotionRequest) returns (AddProductsToPromotionResponse);
}

message Promotions {
  uint32 id = 1;
  string created_at = 2;
  optional string deleted_at = 3;
  string name = 4;
  string starting_datetime = 5;
  string ending_datetime = 6;

}

message PromotionProductInput {
  string product_id = 1;
  float promotional_price = 2;
}

message AddProductsToPromotionRequest {
  string promotion_id = 1;
  repeated PromotionProductInput products = 2;
}

message AddProductsToPromotionResponse {
  string message = 1;
}

message CreateRequest {
  string name = 1;
  string starting_datetime = 2;
  string ending_datetime = 3;
}

message CreateResponse {
  Promotions promotions = 1;
}

message GetRequest {
  uint32 id = 1;
}

message GetResponse {
  Promotions promotions = 1;
}

message UpdateRequest {
  uint32 id = 1;
  optional string name = 2;
  optional string starting_datetime = 3;
  optional string ending_datetime = 4;
}

message UpdateResponse {
  Promotions promotions = 1;
}

message DeleteRequest {
  uint32 id = 1;
}

message DeleteResponse {}

message ListRequest {
  optional uint32 limit = 1;
  optional uint32 offset = 2;
  optional string starting_datetime = 3;
  optional string name = 4;
  optional string ending_datetime = 5;
  optional bool include_deleted = 6;
  optional OrderBy orderby = 7;
}

message OrderBy {
  optional string id = 1;
  optional string created_at = 2;
}

message ListResponse {
  repeated Promotions rows = 1;
  uint32 count = 2;
}
