// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: transaction-service/protos/currency.proto

package currency_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *string                `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	CreatedBy      uint32                 `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy      uint32                 `protobuf:"varint,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy      *uint32                `protobuf:"varint,7,opt,name=deleted_by,json=deletedBy,proto3,oneof" json:"deleted_by,omitempty"`
	Name           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Symbol         string                 `protobuf:"bytes,9,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Abbreviation   string                 `protobuf:"bytes,10,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Decimals       int32                  `protobuf:"varint,11,opt,name=decimals,proto3" json:"decimals,omitempty"`
	CurrencyTypeId uint32                 `protobuf:"varint,12,opt,name=currency_type_id,json=currencyTypeId,proto3" json:"currency_type_id,omitempty"`
	RequesterId    uint32                 `protobuf:"varint,13,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Currency) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Currency) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Currency) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *Currency) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Currency) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *Currency) GetDeletedBy() uint32 {
	if x != nil && x.DeletedBy != nil {
		return *x.DeletedBy
	}
	return 0
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Currency) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *Currency) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *Currency) GetCurrencyTypeId() uint32 {
	if x != nil {
		return x.CurrencyTypeId
	}
	return 0
}

func (x *Currency) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type CreateCurrencyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequesterId    uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol         string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Abbreviation   string                 `protobuf:"bytes,4,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Decimals       int32                  `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	CurrencyTypeId uint32                 `protobuf:"varint,6,opt,name=currency_type_id,json=currencyTypeId,proto3" json:"currency_type_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCurrencyRequest) Reset() {
	*x = CreateCurrencyRequest{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyRequest) ProtoMessage() {}

func (x *CreateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCurrencyRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateCurrencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCurrencyRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateCurrencyRequest) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *CreateCurrencyRequest) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreateCurrencyRequest) GetCurrencyTypeId() uint32 {
	if x != nil {
		return x.CurrencyTypeId
	}
	return 0
}

type CreateCurrencyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequesterId    uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol         string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Abbreviation   string                 `protobuf:"bytes,4,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Decimals       int32                  `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	CurrencyTypeId uint32                 `protobuf:"varint,6,opt,name=currency_type_id,json=currencyTypeId,proto3" json:"currency_type_id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      string                 `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedBy      uint32                 `protobuf:"varint,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy      uint32                 `protobuf:"varint,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy      uint32                 `protobuf:"varint,12,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCurrencyResponse) Reset() {
	*x = CreateCurrencyResponse{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyResponse) ProtoMessage() {}

func (x *CreateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*CreateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCurrencyResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateCurrencyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCurrencyResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateCurrencyResponse) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *CreateCurrencyResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreateCurrencyResponse) GetCurrencyTypeId() uint32 {
	if x != nil {
		return x.CurrencyTypeId
	}
	return 0
}

func (x *CreateCurrencyResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateCurrencyResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateCurrencyResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *CreateCurrencyResponse) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *CreateCurrencyResponse) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *CreateCurrencyResponse) GetDeletedBy() uint32 {
	if x != nil {
		return x.DeletedBy
	}
	return 0
}

type GetCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyRequest) Reset() {
	*x = GetCurrencyRequest{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyRequest) ProtoMessage() {}

func (x *GetCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyRequest.ProtoReflect.Descriptor instead.
func (*GetCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrencyRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCurrencyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequesterId    uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol         string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Abbreviation   string                 `protobuf:"bytes,4,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Decimals       int32                  `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	CurrencyTypeId uint32                 `protobuf:"varint,6,opt,name=currency_type_id,json=currencyTypeId,proto3" json:"currency_type_id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      string                 `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedBy      uint32                 `protobuf:"varint,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy      uint32                 `protobuf:"varint,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy      uint32                 `protobuf:"varint,12,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCurrencyResponse) Reset() {
	*x = GetCurrencyResponse{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyResponse) ProtoMessage() {}

func (x *GetCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyResponse.ProtoReflect.Descriptor instead.
func (*GetCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrencyResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GetCurrencyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCurrencyResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetCurrencyResponse) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *GetCurrencyResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetCurrencyResponse) GetCurrencyTypeId() uint32 {
	if x != nil {
		return x.CurrencyTypeId
	}
	return 0
}

func (x *GetCurrencyResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetCurrencyResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetCurrencyResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *GetCurrencyResponse) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *GetCurrencyResponse) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *GetCurrencyResponse) GetDeletedBy() uint32 {
	if x != nil {
		return x.DeletedBy
	}
	return 0
}

type UpdateCurrencyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId    uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name           *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Symbol         *string                `protobuf:"bytes,4,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Abbreviation   *string                `protobuf:"bytes,5,opt,name=abbreviation,proto3,oneof" json:"abbreviation,omitempty"`
	Decimals       *int32                 `protobuf:"varint,6,opt,name=decimals,proto3,oneof" json:"decimals,omitempty"`
	CurrencyTypeId *uint32                `protobuf:"varint,7,opt,name=currency_type_id,json=currencyTypeId,proto3,oneof" json:"currency_type_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCurrencyRequest) Reset() {
	*x = UpdateCurrencyRequest{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyRequest) ProtoMessage() {}

func (x *UpdateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCurrencyRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCurrencyRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *UpdateCurrencyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCurrencyRequest) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *UpdateCurrencyRequest) GetAbbreviation() string {
	if x != nil && x.Abbreviation != nil {
		return *x.Abbreviation
	}
	return ""
}

func (x *UpdateCurrencyRequest) GetDecimals() int32 {
	if x != nil && x.Decimals != nil {
		return *x.Decimals
	}
	return 0
}

func (x *UpdateCurrencyRequest) GetCurrencyTypeId() uint32 {
	if x != nil && x.CurrencyTypeId != nil {
		return *x.CurrencyTypeId
	}
	return 0
}

type UpdateCurrencyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequesterId    uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol         string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Abbreviation   string                 `protobuf:"bytes,4,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Decimals       int32                  `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	CurrencyTypeId uint32                 `protobuf:"varint,6,opt,name=currency_type_id,json=currencyTypeId,proto3" json:"currency_type_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateCurrencyResponse) Reset() {
	*x = UpdateCurrencyResponse{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyResponse) ProtoMessage() {}

func (x *UpdateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCurrencyResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *UpdateCurrencyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCurrencyResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UpdateCurrencyResponse) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *UpdateCurrencyResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *UpdateCurrencyResponse) GetCurrencyTypeId() uint32 {
	if x != nil {
		return x.CurrencyTypeId
	}
	return 0
}

type DeleteCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyRequest) Reset() {
	*x = DeleteCurrencyRequest{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyRequest) ProtoMessage() {}

func (x *DeleteCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCurrencyRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCurrencyRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type DeleteCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyResponse) Reset() {
	*x = DeleteCurrencyResponse{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyResponse) ProtoMessage() {}

func (x *DeleteCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyResponse.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListCurrencyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          *uint32                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset         *uint32                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	IncludeDeleted *bool                  `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	Name           *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Symbol         *string                `protobuf:"bytes,5,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Abbreviation   *string                `protobuf:"bytes,6,opt,name=abbreviation,proto3,oneof" json:"abbreviation,omitempty"`
	Decimals       *int32                 `protobuf:"varint,7,opt,name=decimals,proto3,oneof" json:"decimals,omitempty"`
	CurrencyTypeId *uint32                `protobuf:"varint,8,opt,name=currency_type_id,json=currencyTypeId,proto3,oneof" json:"currency_type_id,omitempty"`
	Orderby        *OrderBy               `protobuf:"bytes,9,opt,name=orderby,proto3,oneof" json:"orderby,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCurrencyRequest) Reset() {
	*x = ListCurrencyRequest{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrencyRequest) ProtoMessage() {}

func (x *ListCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrencyRequest.ProtoReflect.Descriptor instead.
func (*ListCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{9}
}

func (x *ListCurrencyRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListCurrencyRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListCurrencyRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

func (x *ListCurrencyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListCurrencyRequest) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *ListCurrencyRequest) GetAbbreviation() string {
	if x != nil && x.Abbreviation != nil {
		return *x.Abbreviation
	}
	return ""
}

func (x *ListCurrencyRequest) GetDecimals() int32 {
	if x != nil && x.Decimals != nil {
		return *x.Decimals
	}
	return 0
}

func (x *ListCurrencyRequest) GetCurrencyTypeId() uint32 {
	if x != nil && x.CurrencyTypeId != nil {
		return *x.CurrencyTypeId
	}
	return 0
}

func (x *ListCurrencyRequest) GetOrderby() *OrderBy {
	if x != nil {
		return x.Orderby
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Id            *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{10}
}

func (x *OrderBy) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OrderBy) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *OrderBy) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

type ListCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Currency            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrencyResponse) Reset() {
	*x = ListCurrencyResponse{}
	mi := &file_transaction_service_protos_currency_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrencyResponse) ProtoMessage() {}

func (x *ListCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_protos_currency_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrencyResponse.ProtoReflect.Descriptor instead.
func (*ListCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_protos_currency_proto_rawDescGZIP(), []int{11}
}

func (x *ListCurrencyResponse) GetRows() []*Currency {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListCurrencyResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_transaction_service_protos_currency_proto protoreflect.FileDescriptor

const file_transaction_service_protos_currency_proto_rawDesc = "" +
	"\n" +
	")transaction-service/protos/currency.proto\x12\x0ecurrency_proto\"\xb5\x03\n" +
	"\bCurrency\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\tH\x00R\tdeletedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\rR\tupdatedBy\x12\"\n" +
	"\n" +
	"deleted_by\x18\a \x01(\rH\x01R\tdeletedBy\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\t \x01(\tR\x06symbol\x12\"\n" +
	"\fabbreviation\x18\n" +
	" \x01(\tR\fabbreviation\x12\x1a\n" +
	"\bdecimals\x18\v \x01(\x05R\bdecimals\x12(\n" +
	"\x10currency_type_id\x18\f \x01(\rR\x0ecurrencyTypeId\x12!\n" +
	"\frequester_id\x18\r \x01(\rR\vrequesterIdB\r\n" +
	"\v_deleted_atB\r\n" +
	"\v_deleted_by\"\xd0\x01\n" +
	"\x15CreateCurrencyRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\"\n" +
	"\fabbreviation\x18\x04 \x01(\tR\fabbreviation\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\x05R\bdecimals\x12(\n" +
	"\x10currency_type_id\x18\x06 \x01(\rR\x0ecurrencyTypeId\"\x8b\x03\n" +
	"\x16CreateCurrencyResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\"\n" +
	"\fabbreviation\x18\x04 \x01(\tR\fabbreviation\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\x05R\bdecimals\x12(\n" +
	"\x10currency_type_id\x18\x06 \x01(\rR\x0ecurrencyTypeId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\t \x01(\tR\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\v \x01(\rR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\f \x01(\rR\tdeletedBy\"$\n" +
	"\x12GetCurrencyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x88\x03\n" +
	"\x13GetCurrencyResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\"\n" +
	"\fabbreviation\x18\x04 \x01(\tR\fabbreviation\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\x05R\bdecimals\x12(\n" +
	"\x10currency_type_id\x18\x06 \x01(\rR\x0ecurrencyTypeId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\t \x01(\tR\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\n" +
	" \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\v \x01(\rR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\f \x01(\rR\tdeletedBy\"\xc0\x02\n" +
	"\x15UpdateCurrencyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x04 \x01(\tH\x01R\x06symbol\x88\x01\x01\x12'\n" +
	"\fabbreviation\x18\x05 \x01(\tH\x02R\fabbreviation\x88\x01\x01\x12\x1f\n" +
	"\bdecimals\x18\x06 \x01(\x05H\x03R\bdecimals\x88\x01\x01\x12-\n" +
	"\x10currency_type_id\x18\a \x01(\rH\x04R\x0ecurrencyTypeId\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_symbolB\x0f\n" +
	"\r_abbreviationB\v\n" +
	"\t_decimalsB\x13\n" +
	"\x11_currency_type_id\"\xd1\x01\n" +
	"\x16UpdateCurrencyResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\"\n" +
	"\fabbreviation\x18\x04 \x01(\tR\fabbreviation\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\x05R\bdecimals\x12(\n" +
	"\x10currency_type_id\x18\x06 \x01(\rR\x0ecurrencyTypeId\"J\n" +
	"\x15DeleteCurrencyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\"2\n" +
	"\x16DeleteCurrencyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xde\x03\n" +
	"\x13ListCurrencyRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\rH\x01R\x06offset\x88\x01\x01\x12,\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bH\x02R\x0eincludeDeleted\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x03R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x05 \x01(\tH\x04R\x06symbol\x88\x01\x01\x12'\n" +
	"\fabbreviation\x18\x06 \x01(\tH\x05R\fabbreviation\x88\x01\x01\x12\x1f\n" +
	"\bdecimals\x18\a \x01(\x05H\x06R\bdecimals\x88\x01\x01\x12-\n" +
	"\x10currency_type_id\x18\b \x01(\rH\aR\x0ecurrencyTypeId\x88\x01\x01\x126\n" +
	"\aorderby\x18\t \x01(\v2\x17.currency_proto.OrderByH\bR\aorderby\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x12\n" +
	"\x10_include_deletedB\a\n" +
	"\x05_nameB\t\n" +
	"\a_symbolB\x0f\n" +
	"\r_abbreviationB\v\n" +
	"\t_decimalsB\x13\n" +
	"\x11_currency_type_idB\n" +
	"\n" +
	"\b_orderby\"z\n" +
	"\aOrderBy\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x01R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tH\x02R\tcreatedAt\x88\x01\x01B\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_at\"Z\n" +
	"\x14ListCurrencyResponse\x12,\n" +
	"\x04rows\x18\x01 \x03(\v2\x18.currency_proto.CurrencyR\x04rows\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count2\xbf\x03\n" +
	"\x0fCurrencyService\x12W\n" +
	"\x06Create\x12%.currency_proto.CreateCurrencyRequest\x1a&.currency_proto.CreateCurrencyResponse\x12N\n" +
	"\x03Get\x12\".currency_proto.GetCurrencyRequest\x1a#.currency_proto.GetCurrencyResponse\x12W\n" +
	"\x06Update\x12%.currency_proto.UpdateCurrencyRequest\x1a&.currency_proto.UpdateCurrencyResponse\x12W\n" +
	"\x06Delete\x12%.currency_proto.DeleteCurrencyRequest\x1a&.currency_proto.DeleteCurrencyResponse\x12Q\n" +
	"\x04List\x12#.currency_proto.ListCurrencyRequest\x1a$.currency_proto.ListCurrencyResponseB#Z!./generated_protos/currency_protob\x06proto3"

var (
	file_transaction_service_protos_currency_proto_rawDescOnce sync.Once
	file_transaction_service_protos_currency_proto_rawDescData []byte
)

func file_transaction_service_protos_currency_proto_rawDescGZIP() []byte {
	file_transaction_service_protos_currency_proto_rawDescOnce.Do(func() {
		file_transaction_service_protos_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_service_protos_currency_proto_rawDesc), len(file_transaction_service_protos_currency_proto_rawDesc)))
	})
	return file_transaction_service_protos_currency_proto_rawDescData
}

var file_transaction_service_protos_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transaction_service_protos_currency_proto_goTypes = []any{
	(*Currency)(nil),               // 0: currency_proto.Currency
	(*CreateCurrencyRequest)(nil),  // 1: currency_proto.CreateCurrencyRequest
	(*CreateCurrencyResponse)(nil), // 2: currency_proto.CreateCurrencyResponse
	(*GetCurrencyRequest)(nil),     // 3: currency_proto.GetCurrencyRequest
	(*GetCurrencyResponse)(nil),    // 4: currency_proto.GetCurrencyResponse
	(*UpdateCurrencyRequest)(nil),  // 5: currency_proto.UpdateCurrencyRequest
	(*UpdateCurrencyResponse)(nil), // 6: currency_proto.UpdateCurrencyResponse
	(*DeleteCurrencyRequest)(nil),  // 7: currency_proto.DeleteCurrencyRequest
	(*DeleteCurrencyResponse)(nil), // 8: currency_proto.DeleteCurrencyResponse
	(*ListCurrencyRequest)(nil),    // 9: currency_proto.ListCurrencyRequest
	(*OrderBy)(nil),                // 10: currency_proto.OrderBy
	(*ListCurrencyResponse)(nil),   // 11: currency_proto.ListCurrencyResponse
}
var file_transaction_service_protos_currency_proto_depIdxs = []int32{
	10, // 0: currency_proto.ListCurrencyRequest.orderby:type_name -> currency_proto.OrderBy
	0,  // 1: currency_proto.ListCurrencyResponse.rows:type_name -> currency_proto.Currency
	1,  // 2: currency_proto.CurrencyService.Create:input_type -> currency_proto.CreateCurrencyRequest
	3,  // 3: currency_proto.CurrencyService.Get:input_type -> currency_proto.GetCurrencyRequest
	5,  // 4: currency_proto.CurrencyService.Update:input_type -> currency_proto.UpdateCurrencyRequest
	7,  // 5: currency_proto.CurrencyService.Delete:input_type -> currency_proto.DeleteCurrencyRequest
	9,  // 6: currency_proto.CurrencyService.List:input_type -> currency_proto.ListCurrencyRequest
	2,  // 7: currency_proto.CurrencyService.Create:output_type -> currency_proto.CreateCurrencyResponse
	4,  // 8: currency_proto.CurrencyService.Get:output_type -> currency_proto.GetCurrencyResponse
	6,  // 9: currency_proto.CurrencyService.Update:output_type -> currency_proto.UpdateCurrencyResponse
	8,  // 10: currency_proto.CurrencyService.Delete:output_type -> currency_proto.DeleteCurrencyResponse
	11, // 11: currency_proto.CurrencyService.List:output_type -> currency_proto.ListCurrencyResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_service_protos_currency_proto_init() }
func file_transaction_service_protos_currency_proto_init() {
	if File_transaction_service_protos_currency_proto != nil {
		return
	}
	file_transaction_service_protos_currency_proto_msgTypes[0].OneofWrappers = []any{}
	file_transaction_service_protos_currency_proto_msgTypes[5].OneofWrappers = []any{}
	file_transaction_service_protos_currency_proto_msgTypes[9].OneofWrappers = []any{}
	file_transaction_service_protos_currency_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_service_protos_currency_proto_rawDesc), len(file_transaction_service_protos_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_service_protos_currency_proto_goTypes,
		DependencyIndexes: file_transaction_service_protos_currency_proto_depIdxs,
		MessageInfos:      file_transaction_service_protos_currency_proto_msgTypes,
	}.Build()
	File_transaction_service_protos_currency_proto = out.File
	file_transaction_service_protos_currency_proto_goTypes = nil
	file_transaction_service_protos_currency_proto_depIdxs = nil
}
