// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: products_service/protos/image_folder_path.proto

package image_folder_path_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageFolderPath struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt           *string                `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	ImageFolderSourceId uint32                 `protobuf:"varint,4,opt,name=image_folder_source_id,json=imageFolderSourceId,proto3" json:"image_folder_source_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ImageFolderPath) Reset() {
	*x = ImageFolderPath{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageFolderPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageFolderPath) ProtoMessage() {}

func (x *ImageFolderPath) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageFolderPath.ProtoReflect.Descriptor instead.
func (*ImageFolderPath) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{0}
}

func (x *ImageFolderPath) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageFolderPath) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ImageFolderPath) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *ImageFolderPath) GetImageFolderSourceId() uint32 {
	if x != nil {
		return x.ImageFolderSourceId
	}
	return 0
}

type CreateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ImageFolderSourceId uint32                 `protobuf:"varint,1,opt,name=image_folder_source_id,json=imageFolderSourceId,proto3" json:"image_folder_source_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetImageFolderSourceId() uint32 {
	if x != nil {
		return x.ImageFolderSourceId
	}
	return 0
}

type CreateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Imagefolderpath *ImageFolderPath       `protobuf:"bytes,1,opt,name=imagefolderpath,proto3" json:"imagefolderpath,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetImagefolderpath() *ImageFolderPath {
	if x != nil {
		return x.Imagefolderpath
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Imagefolderpath *ImageFolderPath       `protobuf:"bytes,1,opt,name=imagefolderpath,proto3" json:"imagefolderpath,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetImagefolderpath() *ImageFolderPath {
	if x != nil {
		return x.Imagefolderpath
	}
	return nil
}

type UpdateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageFolderSourceId *uint32                `protobuf:"varint,2,opt,name=image_folder_source_id,json=imageFolderSourceId,proto3,oneof" json:"image_folder_source_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetImageFolderSourceId() uint32 {
	if x != nil && x.ImageFolderSourceId != nil {
		return *x.ImageFolderSourceId
	}
	return 0
}

type UpdateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Imagefolderpath *ImageFolderPath       `protobuf:"bytes,1,opt,name=imagefolderpath,proto3" json:"imagefolderpath,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetImagefolderpath() *ImageFolderPath {
	if x != nil {
		return x.Imagefolderpath
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{8}
}

type ListRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Limit               *uint32                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset              *uint32                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	ImageFolderSourceId *uint32                `protobuf:"varint,3,opt,name=image_folder_source_id,json=imageFolderSourceId,proto3,oneof" json:"image_folder_source_id,omitempty"`
	IncludeDeleted      *bool                  `protobuf:"varint,4,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	Orderby             *OrderBy               `protobuf:"bytes,5,opt,name=orderby,proto3,oneof" json:"orderby,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListRequest) GetImageFolderSourceId() uint32 {
	if x != nil && x.ImageFolderSourceId != nil {
		return *x.ImageFolderSourceId
	}
	return 0
}

func (x *ListRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

func (x *ListRequest) GetOrderby() *OrderBy {
	if x != nil {
		return x.Orderby
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{10}
}

func (x *OrderBy) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *OrderBy) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*ImageFolderPath     `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_path_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_path_proto_rawDescGZIP(), []int{11}
}

func (x *ListResponse) GetRows() []*ImageFolderPath {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_products_service_protos_image_folder_path_proto protoreflect.FileDescriptor

const file_products_service_protos_image_folder_path_proto_rawDesc = "" +
	"\n" +
	"/products_service/protos/image_folder_path.proto\x12\x17image_folder_path_proto\"\xa8\x01\n" +
	"\x0fImageFolderPath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\tH\x00R\tdeletedAt\x88\x01\x01\x123\n" +
	"\x16image_folder_source_id\x18\x04 \x01(\rR\x13imageFolderSourceIdB\r\n" +
	"\v_deleted_at\"D\n" +
	"\rCreateRequest\x123\n" +
	"\x16image_folder_source_id\x18\x01 \x01(\rR\x13imageFolderSourceId\"d\n" +
	"\x0eCreateResponse\x12R\n" +
	"\x0fimagefolderpath\x18\x01 \x01(\v2(.image_folder_path_proto.ImageFolderPathR\x0fimagefolderpath\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"a\n" +
	"\vGetResponse\x12R\n" +
	"\x0fimagefolderpath\x18\x01 \x01(\v2(.image_folder_path_proto.ImageFolderPathR\x0fimagefolderpath\"t\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x128\n" +
	"\x16image_folder_source_id\x18\x02 \x01(\rH\x00R\x13imageFolderSourceId\x88\x01\x01B\x19\n" +
	"\x17_image_folder_source_id\"d\n" +
	"\x0eUpdateResponse\x12R\n" +
	"\x0fimagefolderpath\x18\x01 \x01(\v2(.image_folder_path_proto.ImageFolderPathR\x0fimagefolderpath\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"\xbe\x02\n" +
	"\vListRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\rH\x01R\x06offset\x88\x01\x01\x128\n" +
	"\x16image_folder_source_id\x18\x03 \x01(\rH\x02R\x13imageFolderSourceId\x88\x01\x01\x12,\n" +
	"\x0finclude_deleted\x18\x04 \x01(\bH\x03R\x0eincludeDeleted\x88\x01\x01\x12?\n" +
	"\aorderby\x18\x05 \x01(\v2 .image_folder_path_proto.OrderByH\x04R\aorderby\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x19\n" +
	"\x17_image_folder_source_idB\x12\n" +
	"\x10_include_deletedB\n" +
	"\n" +
	"\b_orderby\"X\n" +
	"\aOrderBy\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tH\x01R\tcreatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_at\"b\n" +
	"\fListResponse\x12<\n" +
	"\x04rows\x18\x01 \x03(\v2(.image_folder_path_proto.ImageFolderPathR\x04rows\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count2\xd0\x03\n" +
	"\x16ImageFolderPathService\x12Y\n" +
	"\x06Create\x12&.image_folder_path_proto.CreateRequest\x1a'.image_folder_path_proto.CreateResponse\x12P\n" +
	"\x03Get\x12#.image_folder_path_proto.GetRequest\x1a$.image_folder_path_proto.GetResponse\x12Y\n" +
	"\x06Update\x12&.image_folder_path_proto.UpdateRequest\x1a'.image_folder_path_proto.UpdateResponse\x12Y\n" +
	"\x06Delete\x12&.image_folder_path_proto.DeleteRequest\x1a'.image_folder_path_proto.DeleteResponse\x12S\n" +
	"\x04List\x12$.image_folder_path_proto.ListRequest\x1a%.image_folder_path_proto.ListResponseB,Z*./generated_protos/image_folder_path_protob\x06proto3"

var (
	file_products_service_protos_image_folder_path_proto_rawDescOnce sync.Once
	file_products_service_protos_image_folder_path_proto_rawDescData []byte
)

func file_products_service_protos_image_folder_path_proto_rawDescGZIP() []byte {
	file_products_service_protos_image_folder_path_proto_rawDescOnce.Do(func() {
		file_products_service_protos_image_folder_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_service_protos_image_folder_path_proto_rawDesc), len(file_products_service_protos_image_folder_path_proto_rawDesc)))
	})
	return file_products_service_protos_image_folder_path_proto_rawDescData
}

var file_products_service_protos_image_folder_path_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_products_service_protos_image_folder_path_proto_goTypes = []any{
	(*ImageFolderPath)(nil), // 0: image_folder_path_proto.ImageFolderPath
	(*CreateRequest)(nil),   // 1: image_folder_path_proto.CreateRequest
	(*CreateResponse)(nil),  // 2: image_folder_path_proto.CreateResponse
	(*GetRequest)(nil),      // 3: image_folder_path_proto.GetRequest
	(*GetResponse)(nil),     // 4: image_folder_path_proto.GetResponse
	(*UpdateRequest)(nil),   // 5: image_folder_path_proto.UpdateRequest
	(*UpdateResponse)(nil),  // 6: image_folder_path_proto.UpdateResponse
	(*DeleteRequest)(nil),   // 7: image_folder_path_proto.DeleteRequest
	(*DeleteResponse)(nil),  // 8: image_folder_path_proto.DeleteResponse
	(*ListRequest)(nil),     // 9: image_folder_path_proto.ListRequest
	(*OrderBy)(nil),         // 10: image_folder_path_proto.OrderBy
	(*ListResponse)(nil),    // 11: image_folder_path_proto.ListResponse
}
var file_products_service_protos_image_folder_path_proto_depIdxs = []int32{
	0,  // 0: image_folder_path_proto.CreateResponse.imagefolderpath:type_name -> image_folder_path_proto.ImageFolderPath
	0,  // 1: image_folder_path_proto.GetResponse.imagefolderpath:type_name -> image_folder_path_proto.ImageFolderPath
	0,  // 2: image_folder_path_proto.UpdateResponse.imagefolderpath:type_name -> image_folder_path_proto.ImageFolderPath
	10, // 3: image_folder_path_proto.ListRequest.orderby:type_name -> image_folder_path_proto.OrderBy
	0,  // 4: image_folder_path_proto.ListResponse.rows:type_name -> image_folder_path_proto.ImageFolderPath
	1,  // 5: image_folder_path_proto.ImageFolderPathService.Create:input_type -> image_folder_path_proto.CreateRequest
	3,  // 6: image_folder_path_proto.ImageFolderPathService.Get:input_type -> image_folder_path_proto.GetRequest
	5,  // 7: image_folder_path_proto.ImageFolderPathService.Update:input_type -> image_folder_path_proto.UpdateRequest
	7,  // 8: image_folder_path_proto.ImageFolderPathService.Delete:input_type -> image_folder_path_proto.DeleteRequest
	9,  // 9: image_folder_path_proto.ImageFolderPathService.List:input_type -> image_folder_path_proto.ListRequest
	2,  // 10: image_folder_path_proto.ImageFolderPathService.Create:output_type -> image_folder_path_proto.CreateResponse
	4,  // 11: image_folder_path_proto.ImageFolderPathService.Get:output_type -> image_folder_path_proto.GetResponse
	6,  // 12: image_folder_path_proto.ImageFolderPathService.Update:output_type -> image_folder_path_proto.UpdateResponse
	8,  // 13: image_folder_path_proto.ImageFolderPathService.Delete:output_type -> image_folder_path_proto.DeleteResponse
	11, // 14: image_folder_path_proto.ImageFolderPathService.List:output_type -> image_folder_path_proto.ListResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_products_service_protos_image_folder_path_proto_init() }
func file_products_service_protos_image_folder_path_proto_init() {
	if File_products_service_protos_image_folder_path_proto != nil {
		return
	}
	file_products_service_protos_image_folder_path_proto_msgTypes[0].OneofWrappers = []any{}
	file_products_service_protos_image_folder_path_proto_msgTypes[5].OneofWrappers = []any{}
	file_products_service_protos_image_folder_path_proto_msgTypes[9].OneofWrappers = []any{}
	file_products_service_protos_image_folder_path_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_service_protos_image_folder_path_proto_rawDesc), len(file_products_service_protos_image_folder_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_service_protos_image_folder_path_proto_goTypes,
		DependencyIndexes: file_products_service_protos_image_folder_path_proto_depIdxs,
		MessageInfos:      file_products_service_protos_image_folder_path_proto_msgTypes,
	}.Build()
	File_products_service_protos_image_folder_path_proto = out.File
	file_products_service_protos_image_folder_path_proto_goTypes = nil
	file_products_service_protos_image_folder_path_proto_depIdxs = nil
}
