// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: transaction-service/protos/currency_type.proto

package currency_type_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyTypeService_Create_FullMethodName = "/currency_type_proto.CurrencyTypeService/Create"
	CurrencyTypeService_Get_FullMethodName    = "/currency_type_proto.CurrencyTypeService/Get"
	CurrencyTypeService_Update_FullMethodName = "/currency_type_proto.CurrencyTypeService/Update"
	CurrencyTypeService_Delete_FullMethodName = "/currency_type_proto.CurrencyTypeService/Delete"
	CurrencyTypeService_List_FullMethodName   = "/currency_type_proto.CurrencyTypeService/List"
)

// CurrencyTypeServiceClient is the client API for CurrencyTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyTypeServiceClient interface {
	Create(ctx context.Context, in *CreateCurrencyTypeRequest, opts ...grpc.CallOption) (*CreateCurrencyTypeResponse, error)
	Get(ctx context.Context, in *GetCurrencyTypeRequest, opts ...grpc.CallOption) (*GetCurrencyTypeResponse, error)
	Update(ctx context.Context, in *UpdateCurrencyTypeRequest, opts ...grpc.CallOption) (*UpdateCurrencyTypeResponse, error)
	Delete(ctx context.Context, in *DeleteCurrencyTypeRequest, opts ...grpc.CallOption) (*DeleteCurrencyTypeResponse, error)
	List(ctx context.Context, in *ListCurrencyTypeRequest, opts ...grpc.CallOption) (*ListCurrencyTypeResponse, error)
}

type currencyTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyTypeServiceClient(cc grpc.ClientConnInterface) CurrencyTypeServiceClient {
	return &currencyTypeServiceClient{cc}
}

func (c *currencyTypeServiceClient) Create(ctx context.Context, in *CreateCurrencyTypeRequest, opts ...grpc.CallOption) (*CreateCurrencyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCurrencyTypeResponse)
	err := c.cc.Invoke(ctx, CurrencyTypeService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyTypeServiceClient) Get(ctx context.Context, in *GetCurrencyTypeRequest, opts ...grpc.CallOption) (*GetCurrencyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrencyTypeResponse)
	err := c.cc.Invoke(ctx, CurrencyTypeService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyTypeServiceClient) Update(ctx context.Context, in *UpdateCurrencyTypeRequest, opts ...grpc.CallOption) (*UpdateCurrencyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCurrencyTypeResponse)
	err := c.cc.Invoke(ctx, CurrencyTypeService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyTypeServiceClient) Delete(ctx context.Context, in *DeleteCurrencyTypeRequest, opts ...grpc.CallOption) (*DeleteCurrencyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCurrencyTypeResponse)
	err := c.cc.Invoke(ctx, CurrencyTypeService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyTypeServiceClient) List(ctx context.Context, in *ListCurrencyTypeRequest, opts ...grpc.CallOption) (*ListCurrencyTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCurrencyTypeResponse)
	err := c.cc.Invoke(ctx, CurrencyTypeService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyTypeServiceServer is the server API for CurrencyTypeService service.
// All implementations must embed UnimplementedCurrencyTypeServiceServer
// for forward compatibility.
type CurrencyTypeServiceServer interface {
	Create(context.Context, *CreateCurrencyTypeRequest) (*CreateCurrencyTypeResponse, error)
	Get(context.Context, *GetCurrencyTypeRequest) (*GetCurrencyTypeResponse, error)
	Update(context.Context, *UpdateCurrencyTypeRequest) (*UpdateCurrencyTypeResponse, error)
	Delete(context.Context, *DeleteCurrencyTypeRequest) (*DeleteCurrencyTypeResponse, error)
	List(context.Context, *ListCurrencyTypeRequest) (*ListCurrencyTypeResponse, error)
	mustEmbedUnimplementedCurrencyTypeServiceServer()
}

// UnimplementedCurrencyTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyTypeServiceServer struct{}

func (UnimplementedCurrencyTypeServiceServer) Create(context.Context, *CreateCurrencyTypeRequest) (*CreateCurrencyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCurrencyTypeServiceServer) Get(context.Context, *GetCurrencyTypeRequest) (*GetCurrencyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCurrencyTypeServiceServer) Update(context.Context, *UpdateCurrencyTypeRequest) (*UpdateCurrencyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCurrencyTypeServiceServer) Delete(context.Context, *DeleteCurrencyTypeRequest) (*DeleteCurrencyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCurrencyTypeServiceServer) List(context.Context, *ListCurrencyTypeRequest) (*ListCurrencyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCurrencyTypeServiceServer) mustEmbedUnimplementedCurrencyTypeServiceServer() {}
func (UnimplementedCurrencyTypeServiceServer) testEmbeddedByValue()                             {}

// UnsafeCurrencyTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyTypeServiceServer will
// result in compilation errors.
type UnsafeCurrencyTypeServiceServer interface {
	mustEmbedUnimplementedCurrencyTypeServiceServer()
}

func RegisterCurrencyTypeServiceServer(s grpc.ServiceRegistrar, srv CurrencyTypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedCurrencyTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyTypeService_ServiceDesc, srv)
}

func _CurrencyTypeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCurrencyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyTypeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyTypeService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyTypeServiceServer).Create(ctx, req.(*CreateCurrencyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyTypeService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrencyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyTypeServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyTypeService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyTypeServiceServer).Get(ctx, req.(*GetCurrencyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyTypeService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCurrencyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyTypeServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyTypeService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyTypeServiceServer).Update(ctx, req.(*UpdateCurrencyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyTypeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCurrencyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyTypeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyTypeService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyTypeServiceServer).Delete(ctx, req.(*DeleteCurrencyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyTypeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCurrencyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyTypeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyTypeService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyTypeServiceServer).List(ctx, req.(*ListCurrencyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyTypeService_ServiceDesc is the grpc.ServiceDesc for CurrencyTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "currency_type_proto.CurrencyTypeService",
	HandlerType: (*CurrencyTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CurrencyTypeService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CurrencyTypeService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CurrencyTypeService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CurrencyTypeService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CurrencyTypeService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction-service/protos/currency_type.proto",
}
