// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: transactions_service/protos/account_has_user.proto

package accounts_has_user_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountHasUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountHasUser) Reset() {
	*x = AccountHasUser{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountHasUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountHasUser) ProtoMessage() {}

func (x *AccountHasUser) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountHasUser.ProtoReflect.Descriptor instead.
func (*AccountHasUser) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{0}
}

func (x *AccountHasUser) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountHasUser) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteResponse) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     *uint32                `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	UserId        *uint32                `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetAccountId() uint32 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *ListRequest) GetUserId() uint32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{10}
}

func (x *OrderBy) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *OrderBy) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*AccountHasUser      `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_account_has_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_account_has_user_proto_rawDescGZIP(), []int{11}
}

func (x *ListResponse) GetRows() []*AccountHasUser {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_transactions_service_protos_account_has_user_proto protoreflect.FileDescriptor

const file_transactions_service_protos_account_has_user_proto_rawDesc = "" +
	"\n" +
	"2transactions_service/protos/account_has_user.proto\x12\x17accounts_has_user_proto\"H\n" +
	"\x0eAccountHasUser\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"G\n" +
	"\rCreateRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"X\n" +
	"\x0eCreateResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\"U\n" +
	"\vGetResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\"G\n" +
	"\rUpdateRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"H\n" +
	"\x0eUpdateResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"H\n" +
	"\x0eDeleteResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"j\n" +
	"\vListRequest\x12\"\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rH\x00R\taccountId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\rH\x01R\x06userId\x88\x01\x01B\r\n" +
	"\v_account_idB\n" +
	"\n" +
	"\b_user_id\"A\n" +
	"\aOrderBy\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"a\n" +
	"\fListResponse\x12;\n" +
	"\x04rows\x18\x01 \x03(\v2'.accounts_has_user_proto.AccountHasUserR\x04rows\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count2\xcf\x03\n" +
	"\x15AccountHasUserService\x12Y\n" +
	"\x06Create\x12&.accounts_has_user_proto.CreateRequest\x1a'.accounts_has_user_proto.CreateResponse\x12P\n" +
	"\x03Get\x12#.accounts_has_user_proto.GetRequest\x1a$.accounts_has_user_proto.GetResponse\x12Y\n" +
	"\x06Update\x12&.accounts_has_user_proto.UpdateRequest\x1a'.accounts_has_user_proto.UpdateResponse\x12Y\n" +
	"\x06Delete\x12&.accounts_has_user_proto.DeleteRequest\x1a'.accounts_has_user_proto.DeleteResponse\x12S\n" +
	"\x04List\x12$.accounts_has_user_proto.ListRequest\x1a%.accounts_has_user_proto.ListResponseB,Z*./generated_protos/accounts_has_user_protob\x06proto3"

var (
	file_transactions_service_protos_account_has_user_proto_rawDescOnce sync.Once
	file_transactions_service_protos_account_has_user_proto_rawDescData []byte
)

func file_transactions_service_protos_account_has_user_proto_rawDescGZIP() []byte {
	file_transactions_service_protos_account_has_user_proto_rawDescOnce.Do(func() {
		file_transactions_service_protos_account_has_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transactions_service_protos_account_has_user_proto_rawDesc), len(file_transactions_service_protos_account_has_user_proto_rawDesc)))
	})
	return file_transactions_service_protos_account_has_user_proto_rawDescData
}

var file_transactions_service_protos_account_has_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transactions_service_protos_account_has_user_proto_goTypes = []any{
	(*AccountHasUser)(nil), // 0: accounts_has_user_proto.AccountHasUser
	(*CreateRequest)(nil),  // 1: accounts_has_user_proto.CreateRequest
	(*CreateResponse)(nil), // 2: accounts_has_user_proto.CreateResponse
	(*GetRequest)(nil),     // 3: accounts_has_user_proto.GetRequest
	(*GetResponse)(nil),    // 4: accounts_has_user_proto.GetResponse
	(*UpdateRequest)(nil),  // 5: accounts_has_user_proto.UpdateRequest
	(*UpdateResponse)(nil), // 6: accounts_has_user_proto.UpdateResponse
	(*DeleteRequest)(nil),  // 7: accounts_has_user_proto.DeleteRequest
	(*DeleteResponse)(nil), // 8: accounts_has_user_proto.DeleteResponse
	(*ListRequest)(nil),    // 9: accounts_has_user_proto.ListRequest
	(*OrderBy)(nil),        // 10: accounts_has_user_proto.OrderBy
	(*ListResponse)(nil),   // 11: accounts_has_user_proto.ListResponse
}
var file_transactions_service_protos_account_has_user_proto_depIdxs = []int32{
	0,  // 0: accounts_has_user_proto.ListResponse.rows:type_name -> accounts_has_user_proto.AccountHasUser
	1,  // 1: accounts_has_user_proto.AccountHasUserService.Create:input_type -> accounts_has_user_proto.CreateRequest
	3,  // 2: accounts_has_user_proto.AccountHasUserService.Get:input_type -> accounts_has_user_proto.GetRequest
	5,  // 3: accounts_has_user_proto.AccountHasUserService.Update:input_type -> accounts_has_user_proto.UpdateRequest
	7,  // 4: accounts_has_user_proto.AccountHasUserService.Delete:input_type -> accounts_has_user_proto.DeleteRequest
	9,  // 5: accounts_has_user_proto.AccountHasUserService.List:input_type -> accounts_has_user_proto.ListRequest
	2,  // 6: accounts_has_user_proto.AccountHasUserService.Create:output_type -> accounts_has_user_proto.CreateResponse
	4,  // 7: accounts_has_user_proto.AccountHasUserService.Get:output_type -> accounts_has_user_proto.GetResponse
	6,  // 8: accounts_has_user_proto.AccountHasUserService.Update:output_type -> accounts_has_user_proto.UpdateResponse
	8,  // 9: accounts_has_user_proto.AccountHasUserService.Delete:output_type -> accounts_has_user_proto.DeleteResponse
	11, // 10: accounts_has_user_proto.AccountHasUserService.List:output_type -> accounts_has_user_proto.ListResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_transactions_service_protos_account_has_user_proto_init() }
func file_transactions_service_protos_account_has_user_proto_init() {
	if File_transactions_service_protos_account_has_user_proto != nil {
		return
	}
	file_transactions_service_protos_account_has_user_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transactions_service_protos_account_has_user_proto_rawDesc), len(file_transactions_service_protos_account_has_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transactions_service_protos_account_has_user_proto_goTypes,
		DependencyIndexes: file_transactions_service_protos_account_has_user_proto_depIdxs,
		MessageInfos:      file_transactions_service_protos_account_has_user_proto_msgTypes,
	}.Build()
	File_transactions_service_protos_account_has_user_proto = out.File
	file_transactions_service_protos_account_has_user_proto_goTypes = nil
	file_transactions_service_protos_account_has_user_proto_depIdxs = nil
}
