// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: permissions_service/protos/permission.proto

package permission_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	InternalName  string                 `protobuf:"bytes,7,opt,name=internal_name,json=internalName,proto3" json:"internal_name,omitempty"`
	ServiceId     uint32                 `protobuf:"varint,8,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	RoleId        uint32                 `protobuf:"varint,9,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{0}
}

func (x *Permission) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Permission) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *Permission) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Permission) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *Permission) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *Permission) GetRoleId() uint32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InternalName  string                 `protobuf:"bytes,3,opt,name=internal_name,json=internalName,proto3" json:"internal_name,omitempty"`
	ServiceId     uint32                 `protobuf:"varint,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRequest) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *CreateRequest) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *CreateRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InternalName  string                 `protobuf:"bytes,4,opt,name=internal_name,json=internalName,proto3" json:"internal_name,omitempty"`
	ServiceId     uint32                 `protobuf:"varint,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateResponse) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *CreateResponse) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{4}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	InternalName  string                 `protobuf:"bytes,7,opt,name=internal_name,json=internalName,proto3" json:"internal_name,omitempty"`
	ServiceId     uint32                 `protobuf:"varint,8,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetResponse) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *GetResponse) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

type ListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          *uint32                `protobuf:"varint,9,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset         *uint32                `protobuf:"varint,10,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	IncludeDeleted *bool                  `protobuf:"varint,11,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	OrderBy        *OrderBy               `protobuf:"bytes,12,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
	Name           *string                `protobuf:"bytes,13,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,14,opt,name=description,proto3,oneof" json:"description,omitempty"`
	InternalName   *string                `protobuf:"bytes,15,opt,name=internal_name,json=internalName,proto3,oneof" json:"internal_name,omitempty"`
	ServiceId      *uint32                `protobuf:"varint,16,opt,name=service_id,json=serviceId,proto3,oneof" json:"service_id,omitempty"`
	IsActive       *bool                  `protobuf:"varint,17,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	RoleId         *uint32                `protobuf:"varint,18,opt,name=role_id,json=roleId,proto3,oneof" json:"role_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{7}
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

func (x *ListRequest) GetOrderBy() *OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *ListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListRequest) GetInternalName() string {
	if x != nil && x.InternalName != nil {
		return *x.InternalName
	}
	return ""
}

func (x *ListRequest) GetServiceId() uint32 {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return 0
}

func (x *ListRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListRequest) GetRoleId() uint32 {
	if x != nil && x.RoleId != nil {
		return *x.RoleId
	}
	return 0
}

type ListByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint32               `protobuf:"varint,18,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByIdsRequest) Reset() {
	*x = ListByIdsRequest{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByIdsRequest) ProtoMessage() {}

func (x *ListByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByIdsRequest.ProtoReflect.Descriptor instead.
func (*ListByIdsRequest) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{8}
}

func (x *ListByIdsRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,19,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByIdsResponse) Reset() {
	*x = ListByIdsResponse{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByIdsResponse) ProtoMessage() {}

func (x *ListByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByIdsResponse.ProtoReflect.Descriptor instead.
func (*ListByIdsResponse) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{9}
}

func (x *ListByIdsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,20,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{10}
}

func (x *OrderBy) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *OrderBy) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Permission          `protobuf:"bytes,22,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         uint32                 `protobuf:"varint,23,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{11}
}

func (x *ListResponse) GetRows() []*Permission {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,24,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,25,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,26,opt,name=description,proto3,oneof" json:"description,omitempty"`
	InternalName  *string                `protobuf:"bytes,27,opt,name=internal_name,json=internalName,proto3,oneof" json:"internal_name,omitempty"`
	ServiceId     *uint32                `protobuf:"varint,28,opt,name=service_id,json=serviceId,proto3,oneof" json:"service_id,omitempty"`
	IsActive      *bool                  `protobuf:"varint,29,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRequest) GetInternalName() string {
	if x != nil && x.InternalName != nil {
		return *x.InternalName
	}
	return ""
}

func (x *UpdateRequest) GetServiceId() uint32 {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return 0
}

func (x *UpdateRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,30,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Name          string                 `protobuf:"bytes,31,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,32,opt,name=description,proto3" json:"description,omitempty"`
	InternalName  string                 `protobuf:"bytes,33,opt,name=internal_name,json=internalName,proto3" json:"internal_name,omitempty"`
	ServiceId     uint32                 `protobuf:"varint,34,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_permissions_service_protos_permission_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_permissions_service_protos_permission_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_permissions_service_protos_permission_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateResponse) GetInternalName() string {
	if x != nil {
		return x.InternalName
	}
	return ""
}

func (x *UpdateResponse) GetServiceId() uint32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

var File_permissions_service_protos_permission_proto protoreflect.FileDescriptor

const file_permissions_service_protos_permission_proto_rawDesc = "" +
	"\n" +
	"+permissions_service/protos/permission.proto\x12\x10permission_proto\"\x9e\x02\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\tH\x00R\tdeletedAt\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12#\n" +
	"\rinternal_name\x18\a \x01(\tR\finternalName\x12\x1d\n" +
	"\n" +
	"service_id\x18\b \x01(\rR\tserviceId\x12\x17\n" +
	"\arole_id\x18\t \x01(\rR\x06roleIdB\r\n" +
	"\v_deleted_at\"\xa6\x01\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rinternal_name\x18\x03 \x01(\tR\finternalName\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\rR\tserviceId\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"\xa7\x01\n" +
	"\x0eCreateResponse\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rinternal_name\x18\x04 \x01(\tR\finternalName\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\rR\tserviceId\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"J\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\xa4\x01\n" +
	"\vGetResponse\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12#\n" +
	"\rinternal_name\x18\a \x01(\tR\finternalName\x12\x1d\n" +
	"\n" +
	"service_id\x18\b \x01(\rR\tserviceId\"\x86\x04\n" +
	"\vListRequest\x12\x19\n" +
	"\x05limit\x18\t \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\n" +
	" \x01(\rH\x01R\x06offset\x88\x01\x01\x12,\n" +
	"\x0finclude_deleted\x18\v \x01(\bH\x02R\x0eincludeDeleted\x88\x01\x01\x129\n" +
	"\border_by\x18\f \x01(\v2\x19.permission_proto.OrderByH\x03R\aorderBy\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\r \x01(\tH\x04R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x0e \x01(\tH\x05R\vdescription\x88\x01\x01\x12(\n" +
	"\rinternal_name\x18\x0f \x01(\tH\x06R\finternalName\x88\x01\x01\x12\"\n" +
	"\n" +
	"service_id\x18\x10 \x01(\rH\aR\tserviceId\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x11 \x01(\bH\bR\bisActive\x88\x01\x01\x12\x1c\n" +
	"\arole_id\x18\x12 \x01(\rH\tR\x06roleId\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x12\n" +
	"\x10_include_deletedB\v\n" +
	"\t_order_byB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_internal_nameB\r\n" +
	"\v_service_idB\f\n" +
	"\n" +
	"_is_activeB\n" +
	"\n" +
	"\b_role_id\"$\n" +
	"\x10ListByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x12 \x03(\rR\x03ids\"S\n" +
	"\x11ListByIdsResponse\x12>\n" +
	"\vpermissions\x18\x13 \x03(\v2\x1c.permission_proto.PermissionR\vpermissions\"X\n" +
	"\aOrderBy\x12\x13\n" +
	"\x02id\x18\x14 \x01(\tH\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x15 \x01(\tH\x01R\tcreatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_at\"V\n" +
	"\fListResponse\x120\n" +
	"\x04rows\x18\x16 \x03(\v2\x1c.permission_proto.PermissionR\x04rows\x12\x14\n" +
	"\x05count\x18\x17 \x01(\rR\x05count\"\x97\x02\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x18 \x01(\rR\x02id\x12\x17\n" +
	"\x04name\x18\x19 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x1a \x01(\tH\x01R\vdescription\x88\x01\x01\x12(\n" +
	"\rinternal_name\x18\x1b \x01(\tH\x02R\finternalName\x88\x01\x01\x12\"\n" +
	"\n" +
	"service_id\x18\x1c \x01(\rH\x03R\tserviceId\x88\x01\x01\x12 \n" +
	"\tis_active\x18\x1d \x01(\bH\x04R\bisActive\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_internal_nameB\r\n" +
	"\v_service_idB\f\n" +
	"\n" +
	"_is_active\"\xa7\x01\n" +
	"\x0eUpdateResponse\x12\x1b\n" +
	"\tis_active\x18\x1e \x01(\bR\bisActive\x12\x12\n" +
	"\x04name\x18\x1f \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18  \x01(\tR\vdescription\x12#\n" +
	"\rinternal_name\x18! \x01(\tR\finternalName\x12\x1d\n" +
	"\n" +
	"service_id\x18\" \x01(\rR\tserviceId2\xdb\x03\n" +
	"\x11PermissionService\x12K\n" +
	"\x06Create\x12\x1f.permission_proto.CreateRequest\x1a .permission_proto.CreateResponse\x12K\n" +
	"\x06Delete\x12\x1f.permission_proto.DeleteRequest\x1a .permission_proto.DeleteResponse\x12E\n" +
	"\x04List\x12\x1d.permission_proto.ListRequest\x1a\x1e.permission_proto.ListResponse\x12K\n" +
	"\x06Update\x12\x1f.permission_proto.UpdateRequest\x1a .permission_proto.UpdateResponse\x12B\n" +
	"\x03Get\x12\x1c.permission_proto.GetRequest\x1a\x1d.permission_proto.GetResponse\x12T\n" +
	"\tListByIds\x12\".permission_proto.ListByIdsRequest\x1a#.permission_proto.ListByIdsResponseB%Z#./generated_protos/permission_protob\x06proto3"

var (
	file_permissions_service_protos_permission_proto_rawDescOnce sync.Once
	file_permissions_service_protos_permission_proto_rawDescData []byte
)

func file_permissions_service_protos_permission_proto_rawDescGZIP() []byte {
	file_permissions_service_protos_permission_proto_rawDescOnce.Do(func() {
		file_permissions_service_protos_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_permissions_service_protos_permission_proto_rawDesc), len(file_permissions_service_protos_permission_proto_rawDesc)))
	})
	return file_permissions_service_protos_permission_proto_rawDescData
}

var file_permissions_service_protos_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_permissions_service_protos_permission_proto_goTypes = []any{
	(*Permission)(nil),        // 0: permission_proto.Permission
	(*CreateRequest)(nil),     // 1: permission_proto.CreateRequest
	(*CreateResponse)(nil),    // 2: permission_proto.CreateResponse
	(*DeleteRequest)(nil),     // 3: permission_proto.DeleteRequest
	(*DeleteResponse)(nil),    // 4: permission_proto.DeleteResponse
	(*GetRequest)(nil),        // 5: permission_proto.GetRequest
	(*GetResponse)(nil),       // 6: permission_proto.GetResponse
	(*ListRequest)(nil),       // 7: permission_proto.ListRequest
	(*ListByIdsRequest)(nil),  // 8: permission_proto.ListByIdsRequest
	(*ListByIdsResponse)(nil), // 9: permission_proto.ListByIdsResponse
	(*OrderBy)(nil),           // 10: permission_proto.OrderBy
	(*ListResponse)(nil),      // 11: permission_proto.ListResponse
	(*UpdateRequest)(nil),     // 12: permission_proto.UpdateRequest
	(*UpdateResponse)(nil),    // 13: permission_proto.UpdateResponse
}
var file_permissions_service_protos_permission_proto_depIdxs = []int32{
	10, // 0: permission_proto.ListRequest.order_by:type_name -> permission_proto.OrderBy
	0,  // 1: permission_proto.ListByIdsResponse.permissions:type_name -> permission_proto.Permission
	0,  // 2: permission_proto.ListResponse.rows:type_name -> permission_proto.Permission
	1,  // 3: permission_proto.PermissionService.Create:input_type -> permission_proto.CreateRequest
	3,  // 4: permission_proto.PermissionService.Delete:input_type -> permission_proto.DeleteRequest
	7,  // 5: permission_proto.PermissionService.List:input_type -> permission_proto.ListRequest
	12, // 6: permission_proto.PermissionService.Update:input_type -> permission_proto.UpdateRequest
	5,  // 7: permission_proto.PermissionService.Get:input_type -> permission_proto.GetRequest
	8,  // 8: permission_proto.PermissionService.ListByIds:input_type -> permission_proto.ListByIdsRequest
	2,  // 9: permission_proto.PermissionService.Create:output_type -> permission_proto.CreateResponse
	4,  // 10: permission_proto.PermissionService.Delete:output_type -> permission_proto.DeleteResponse
	11, // 11: permission_proto.PermissionService.List:output_type -> permission_proto.ListResponse
	13, // 12: permission_proto.PermissionService.Update:output_type -> permission_proto.UpdateResponse
	6,  // 13: permission_proto.PermissionService.Get:output_type -> permission_proto.GetResponse
	9,  // 14: permission_proto.PermissionService.ListByIds:output_type -> permission_proto.ListByIdsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_permissions_service_protos_permission_proto_init() }
func file_permissions_service_protos_permission_proto_init() {
	if File_permissions_service_protos_permission_proto != nil {
		return
	}
	file_permissions_service_protos_permission_proto_msgTypes[0].OneofWrappers = []any{}
	file_permissions_service_protos_permission_proto_msgTypes[7].OneofWrappers = []any{}
	file_permissions_service_protos_permission_proto_msgTypes[10].OneofWrappers = []any{}
	file_permissions_service_protos_permission_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_permissions_service_protos_permission_proto_rawDesc), len(file_permissions_service_protos_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_permissions_service_protos_permission_proto_goTypes,
		DependencyIndexes: file_permissions_service_protos_permission_proto_depIdxs,
		MessageInfos:      file_permissions_service_protos_permission_proto_msgTypes,
	}.Build()
	File_permissions_service_protos_permission_proto = out.File
	file_permissions_service_protos_permission_proto_goTypes = nil
	file_permissions_service_protos_permission_proto_depIdxs = nil
}
