// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: transactions_notifier_service/protos/whatsapp_config.proto

package whatsapp_config_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WhatsappConfigService_Create_FullMethodName = "/whatsapp_config_proto.WhatsappConfigService/Create"
	WhatsappConfigService_Get_FullMethodName    = "/whatsapp_config_proto.WhatsappConfigService/Get"
)

// WhatsappConfigServiceClient is the client API for WhatsappConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WhatsappConfigServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type whatsappConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWhatsappConfigServiceClient(cc grpc.ClientConnInterface) WhatsappConfigServiceClient {
	return &whatsappConfigServiceClient{cc}
}

func (c *whatsappConfigServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, WhatsappConfigService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *whatsappConfigServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, WhatsappConfigService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhatsappConfigServiceServer is the server API for WhatsappConfigService service.
// All implementations must embed UnimplementedWhatsappConfigServiceServer
// for forward compatibility.
type WhatsappConfigServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedWhatsappConfigServiceServer()
}

// UnimplementedWhatsappConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWhatsappConfigServiceServer struct{}

func (UnimplementedWhatsappConfigServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedWhatsappConfigServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWhatsappConfigServiceServer) mustEmbedUnimplementedWhatsappConfigServiceServer() {}
func (UnimplementedWhatsappConfigServiceServer) testEmbeddedByValue()                               {}

// UnsafeWhatsappConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhatsappConfigServiceServer will
// result in compilation errors.
type UnsafeWhatsappConfigServiceServer interface {
	mustEmbedUnimplementedWhatsappConfigServiceServer()
}

func RegisterWhatsappConfigServiceServer(s grpc.ServiceRegistrar, srv WhatsappConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedWhatsappConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WhatsappConfigService_ServiceDesc, srv)
}

func _WhatsappConfigService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsappConfigServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsappConfigService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsappConfigServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WhatsappConfigService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsappConfigServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WhatsappConfigService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsappConfigServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WhatsappConfigService_ServiceDesc is the grpc.ServiceDesc for WhatsappConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WhatsappConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whatsapp_config_proto.WhatsappConfigService",
	HandlerType: (*WhatsappConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _WhatsappConfigService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WhatsappConfigService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions_notifier_service/protos/whatsapp_config.proto",
}
