syntax = "proto3";

package images_proto;

option go_package = "./generated_protos/images_proto";

service ImagesService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc List(ListRequest) returns (ListResponse);
}

message Images {
  uint32 id = 1;
  string created_at = 2;
  string updated_at = 3;
  optional string deleted_at = 4;
  uint32 created_by = 5;
  uint32 updated_by = 6;
  optional uint32 deleted_by = 7;
  uint32 media_type_id = 8;
  string name = 9;
  uint32 folder_id = 10;
  string uuid = 11;
}

message CreateRequest {
  string requester_uuid = 1;
  uint32 media_type_id = 2;
  string name = 3;
  uint32 folder_id = 4;
  string uuid = 5;
  
}

message CreateResponse {
  string requester_uuid = 1;
  uint32 media_type_id = 2;
  string name = 3;
  uint32 folder_id = 4;
  string uuid = 5;
  string created_at = 6;
  string updated_at = 7;
  string deleted_at = 8;
  uint32 created_by = 9;
  uint32 updated_by = 10;
  uint32 deleted_by = 11;
}

message GetRequest {
  uint32 id = 1;
}

message GetResponse {
  string requester_uuid = 1;
  uint32 media_type_id = 2;
   string name = 3;
  uint32 folder_id = 4;
  string uuid = 5;
  string created_at = 6;
  string updated_at = 7;
  string deleted_at = 8;
  uint32 created_by = 9;
  uint32 updated_by = 10;
  uint32 deleted_by = 11;
}

message UpdateRequest {
  uint32 id = 1;
  string requester_uuid = 2;
  optional uint32 media_type_id = 3;
  optional string name = 4;
  optional string uuid = 5;
  uint32 folder_id = 6;
}

message UpdateResponse {
  string requester_uuid = 1;
  uint32 media_type_id = 2;
  string name = 3;
  uint32 folder_id = 4;
  string uuid = 5;
  string created_at = 6;
  string updated_at = 7;
  string deleted_at = 8;
  uint32 created_by = 9;
  uint32 updated_by = 10;
  uint32 deleted_by = 11;
}

message DeleteRequest {
  uint32 id = 1;
  string requester_uuid = 2;
}

message DeleteResponse {
  string message = 1;
}

message ListRequest {
  optional uint32 limit = 1;
  optional uint32 offset = 2;
  optional uint32 media_type_id = 3;
  optional string name = 4;
  uint32 folder_id = 5;
  string uuid = 6;
  optional bool include_deleted = 7;
  optional OrderBy orderby = 8;
}

message OrderBy {
  optional string id = 1;
  optional string created_at = 2;
}

message ListResponse {
  repeated Images rows = 1;
  uint32 count = 2;
}
