// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: products_service/protos/image_folder_source.proto

package image_folder_source_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageFolderSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	AcessKey      *string                `protobuf:"bytes,6,opt,name=acess_key,json=acessKey,proto3,oneof" json:"acess_key,omitempty"`
	SecretKey     *string                `protobuf:"bytes,7,opt,name=secret_key,json=secretKey,proto3,oneof" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageFolderSource) Reset() {
	*x = ImageFolderSource{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageFolderSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageFolderSource) ProtoMessage() {}

func (x *ImageFolderSource) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageFolderSource.ProtoReflect.Descriptor instead.
func (*ImageFolderSource) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{0}
}

func (x *ImageFolderSource) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ImageFolderSource) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ImageFolderSource) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *ImageFolderSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageFolderSource) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ImageFolderSource) GetAcessKey() string {
	if x != nil && x.AcessKey != nil {
		return *x.AcessKey
	}
	return ""
}

func (x *ImageFolderSource) GetSecretKey() string {
	if x != nil && x.SecretKey != nil {
		return *x.SecretKey
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	AcessKey      *string                `protobuf:"bytes,3,opt,name=acess_key,json=acessKey,proto3,oneof" json:"acess_key,omitempty"`
	SecretKey     *string                `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3,oneof" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CreateRequest) GetAcessKey() string {
	if x != nil && x.AcessKey != nil {
		return *x.AcessKey
	}
	return ""
}

func (x *CreateRequest) GetSecretKey() string {
	if x != nil && x.SecretKey != nil {
		return *x.SecretKey
	}
	return ""
}

type CreateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Imagefoldersource *ImageFolderSource     `protobuf:"bytes,1,opt,name=imagefoldersource,proto3" json:"imagefoldersource,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetImagefoldersource() *ImageFolderSource {
	if x != nil {
		return x.Imagefoldersource
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Imagefoldersource *ImageFolderSource     `protobuf:"bytes,1,opt,name=imagefoldersource,proto3" json:"imagefoldersource,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetImagefoldersource() *ImageFolderSource {
	if x != nil {
		return x.Imagefoldersource
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BaseUrl       *string                `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3,oneof" json:"base_url,omitempty"`
	AcessKey      *string                `protobuf:"bytes,4,opt,name=acess_key,json=acessKey,proto3,oneof" json:"acess_key,omitempty"`
	SecretKey     *string                `protobuf:"bytes,5,opt,name=secret_key,json=secretKey,proto3,oneof" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRequest) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *UpdateRequest) GetAcessKey() string {
	if x != nil && x.AcessKey != nil {
		return *x.AcessKey
	}
	return ""
}

func (x *UpdateRequest) GetSecretKey() string {
	if x != nil && x.SecretKey != nil {
		return *x.SecretKey
	}
	return ""
}

type UpdateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Imagefoldersource *ImageFolderSource     `protobuf:"bytes,1,opt,name=imagefoldersource,proto3" json:"imagefoldersource,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetImagefoldersource() *ImageFolderSource {
	if x != nil {
		return x.Imagefoldersource
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          *uint32                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset         *uint32                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Name           *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BaseUrl        *string                `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3,oneof" json:"base_url,omitempty"`
	AcessKey       *string                `protobuf:"bytes,5,opt,name=acess_key,json=acessKey,proto3,oneof" json:"acess_key,omitempty"`
	SecretKey      *string                `protobuf:"bytes,6,opt,name=secret_key,json=secretKey,proto3,oneof" json:"secret_key,omitempty"`
	IncludeDeleted *bool                  `protobuf:"varint,7,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	Orderby        *OrderBy               `protobuf:"bytes,8,opt,name=orderby,proto3,oneof" json:"orderby,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{9}
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListRequest) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

func (x *ListRequest) GetAcessKey() string {
	if x != nil && x.AcessKey != nil {
		return *x.AcessKey
	}
	return ""
}

func (x *ListRequest) GetSecretKey() string {
	if x != nil && x.SecretKey != nil {
		return *x.SecretKey
	}
	return ""
}

func (x *ListRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

func (x *ListRequest) GetOrderby() *OrderBy {
	if x != nil {
		return x.Orderby
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{10}
}

func (x *OrderBy) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *OrderBy) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*ImageFolderSource   `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_service_protos_image_folder_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_products_service_protos_image_folder_source_proto_rawDescGZIP(), []int{11}
}

func (x *ListResponse) GetRows() []*ImageFolderSource {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_products_service_protos_image_folder_source_proto protoreflect.FileDescriptor

const file_products_service_protos_image_folder_source_proto_rawDesc = "" +
	"\n" +
	"1products_service/protos/image_folder_source.proto\x12\x19image_folder_source_proto\"\x87\x02\n" +
	"\x11ImageFolderSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\tH\x00R\tdeletedAt\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12 \n" +
	"\tacess_key\x18\x06 \x01(\tH\x01R\bacessKey\x88\x01\x01\x12\"\n" +
	"\n" +
	"secret_key\x18\a \x01(\tH\x02R\tsecretKey\x88\x01\x01B\r\n" +
	"\v_deleted_atB\f\n" +
	"\n" +
	"_acess_keyB\r\n" +
	"\v_secret_key\"\xa1\x01\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12 \n" +
	"\tacess_key\x18\x03 \x01(\tH\x00R\bacessKey\x88\x01\x01\x12\"\n" +
	"\n" +
	"secret_key\x18\x04 \x01(\tH\x01R\tsecretKey\x88\x01\x01B\f\n" +
	"\n" +
	"_acess_keyB\r\n" +
	"\v_secret_key\"l\n" +
	"\x0eCreateResponse\x12Z\n" +
	"\x11imagefoldersource\x18\x01 \x01(\v2,.image_folder_source_proto.ImageFolderSourceR\x11imagefoldersource\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"i\n" +
	"\vGetResponse\x12Z\n" +
	"\x11imagefoldersource\x18\x01 \x01(\v2,.image_folder_source_proto.ImageFolderSourceR\x11imagefoldersource\"\xd1\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1e\n" +
	"\bbase_url\x18\x03 \x01(\tH\x01R\abaseUrl\x88\x01\x01\x12 \n" +
	"\tacess_key\x18\x04 \x01(\tH\x02R\bacessKey\x88\x01\x01\x12\"\n" +
	"\n" +
	"secret_key\x18\x05 \x01(\tH\x03R\tsecretKey\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_base_urlB\f\n" +
	"\n" +
	"_acess_keyB\r\n" +
	"\v_secret_key\"l\n" +
	"\x0eUpdateResponse\x12Z\n" +
	"\x11imagefoldersource\x18\x01 \x01(\v2,.image_folder_source_proto.ImageFolderSourceR\x11imagefoldersource\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x9d\x03\n" +
	"\vListRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\rH\x01R\x06offset\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12\x1e\n" +
	"\bbase_url\x18\x04 \x01(\tH\x03R\abaseUrl\x88\x01\x01\x12 \n" +
	"\tacess_key\x18\x05 \x01(\tH\x04R\bacessKey\x88\x01\x01\x12\"\n" +
	"\n" +
	"secret_key\x18\x06 \x01(\tH\x05R\tsecretKey\x88\x01\x01\x12,\n" +
	"\x0finclude_deleted\x18\a \x01(\bH\x06R\x0eincludeDeleted\x88\x01\x01\x12A\n" +
	"\aorderby\x18\b \x01(\v2\".image_folder_source_proto.OrderByH\aR\aorderby\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\a\n" +
	"\x05_nameB\v\n" +
	"\t_base_urlB\f\n" +
	"\n" +
	"_acess_keyB\r\n" +
	"\v_secret_keyB\x12\n" +
	"\x10_include_deletedB\n" +
	"\n" +
	"\b_orderby\"X\n" +
	"\aOrderBy\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tH\x01R\tcreatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_at\"f\n" +
	"\fListResponse\x12@\n" +
	"\x04rows\x18\x01 \x03(\v2,.image_folder_source_proto.ImageFolderSourceR\x04rows\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count2\xe6\x03\n" +
	"\x18ImageFolderSourceService\x12]\n" +
	"\x06Create\x12(.image_folder_source_proto.CreateRequest\x1a).image_folder_source_proto.CreateResponse\x12T\n" +
	"\x03Get\x12%.image_folder_source_proto.GetRequest\x1a&.image_folder_source_proto.GetResponse\x12]\n" +
	"\x06Update\x12(.image_folder_source_proto.UpdateRequest\x1a).image_folder_source_proto.UpdateResponse\x12]\n" +
	"\x06Delete\x12(.image_folder_source_proto.DeleteRequest\x1a).image_folder_source_proto.DeleteResponse\x12W\n" +
	"\x04List\x12&.image_folder_source_proto.ListRequest\x1a'.image_folder_source_proto.ListResponseB.Z,./generated_protos/image_folder_source_protob\x06proto3"

var (
	file_products_service_protos_image_folder_source_proto_rawDescOnce sync.Once
	file_products_service_protos_image_folder_source_proto_rawDescData []byte
)

func file_products_service_protos_image_folder_source_proto_rawDescGZIP() []byte {
	file_products_service_protos_image_folder_source_proto_rawDescOnce.Do(func() {
		file_products_service_protos_image_folder_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_service_protos_image_folder_source_proto_rawDesc), len(file_products_service_protos_image_folder_source_proto_rawDesc)))
	})
	return file_products_service_protos_image_folder_source_proto_rawDescData
}

var file_products_service_protos_image_folder_source_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_products_service_protos_image_folder_source_proto_goTypes = []any{
	(*ImageFolderSource)(nil), // 0: image_folder_source_proto.ImageFolderSource
	(*CreateRequest)(nil),     // 1: image_folder_source_proto.CreateRequest
	(*CreateResponse)(nil),    // 2: image_folder_source_proto.CreateResponse
	(*GetRequest)(nil),        // 3: image_folder_source_proto.GetRequest
	(*GetResponse)(nil),       // 4: image_folder_source_proto.GetResponse
	(*UpdateRequest)(nil),     // 5: image_folder_source_proto.UpdateRequest
	(*UpdateResponse)(nil),    // 6: image_folder_source_proto.UpdateResponse
	(*DeleteRequest)(nil),     // 7: image_folder_source_proto.DeleteRequest
	(*DeleteResponse)(nil),    // 8: image_folder_source_proto.DeleteResponse
	(*ListRequest)(nil),       // 9: image_folder_source_proto.ListRequest
	(*OrderBy)(nil),           // 10: image_folder_source_proto.OrderBy
	(*ListResponse)(nil),      // 11: image_folder_source_proto.ListResponse
}
var file_products_service_protos_image_folder_source_proto_depIdxs = []int32{
	0,  // 0: image_folder_source_proto.CreateResponse.imagefoldersource:type_name -> image_folder_source_proto.ImageFolderSource
	0,  // 1: image_folder_source_proto.GetResponse.imagefoldersource:type_name -> image_folder_source_proto.ImageFolderSource
	0,  // 2: image_folder_source_proto.UpdateResponse.imagefoldersource:type_name -> image_folder_source_proto.ImageFolderSource
	10, // 3: image_folder_source_proto.ListRequest.orderby:type_name -> image_folder_source_proto.OrderBy
	0,  // 4: image_folder_source_proto.ListResponse.rows:type_name -> image_folder_source_proto.ImageFolderSource
	1,  // 5: image_folder_source_proto.ImageFolderSourceService.Create:input_type -> image_folder_source_proto.CreateRequest
	3,  // 6: image_folder_source_proto.ImageFolderSourceService.Get:input_type -> image_folder_source_proto.GetRequest
	5,  // 7: image_folder_source_proto.ImageFolderSourceService.Update:input_type -> image_folder_source_proto.UpdateRequest
	7,  // 8: image_folder_source_proto.ImageFolderSourceService.Delete:input_type -> image_folder_source_proto.DeleteRequest
	9,  // 9: image_folder_source_proto.ImageFolderSourceService.List:input_type -> image_folder_source_proto.ListRequest
	2,  // 10: image_folder_source_proto.ImageFolderSourceService.Create:output_type -> image_folder_source_proto.CreateResponse
	4,  // 11: image_folder_source_proto.ImageFolderSourceService.Get:output_type -> image_folder_source_proto.GetResponse
	6,  // 12: image_folder_source_proto.ImageFolderSourceService.Update:output_type -> image_folder_source_proto.UpdateResponse
	8,  // 13: image_folder_source_proto.ImageFolderSourceService.Delete:output_type -> image_folder_source_proto.DeleteResponse
	11, // 14: image_folder_source_proto.ImageFolderSourceService.List:output_type -> image_folder_source_proto.ListResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_products_service_protos_image_folder_source_proto_init() }
func file_products_service_protos_image_folder_source_proto_init() {
	if File_products_service_protos_image_folder_source_proto != nil {
		return
	}
	file_products_service_protos_image_folder_source_proto_msgTypes[0].OneofWrappers = []any{}
	file_products_service_protos_image_folder_source_proto_msgTypes[1].OneofWrappers = []any{}
	file_products_service_protos_image_folder_source_proto_msgTypes[5].OneofWrappers = []any{}
	file_products_service_protos_image_folder_source_proto_msgTypes[9].OneofWrappers = []any{}
	file_products_service_protos_image_folder_source_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_service_protos_image_folder_source_proto_rawDesc), len(file_products_service_protos_image_folder_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_service_protos_image_folder_source_proto_goTypes,
		DependencyIndexes: file_products_service_protos_image_folder_source_proto_depIdxs,
		MessageInfos:      file_products_service_protos_image_folder_source_proto_msgTypes,
	}.Build()
	File_products_service_protos_image_folder_source_proto = out.File
	file_products_service_protos_image_folder_source_proto_goTypes = nil
	file_products_service_protos_image_folder_source_proto_depIdxs = nil
}
