// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: transactions_service/protos/transaction.proto

package transaction_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *string                `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	CreatedBy            uint32                 `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            uint32                 `protobuf:"varint,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy            *uint32                `protobuf:"varint,7,opt,name=deleted_by,json=deletedBy,proto3,oneof" json:"deleted_by,omitempty"`
	OriginAccountId      uint32                 `protobuf:"varint,8,opt,name=origin_account_id,json=originAccountId,proto3" json:"origin_account_id,omitempty"`
	DestinationAccountId uint32                 `protobuf:"varint,9,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	TransactionTypeId    uint32                 `protobuf:"varint,10,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,11,opt,name=amount,proto3" json:"amount,omitempty"`
	ExchangeId           uint32                 `protobuf:"varint,12,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Successful           bool                   `protobuf:"varint,13,opt,name=successful,proto3" json:"successful,omitempty"`
	Observation          *string                `protobuf:"bytes,14,opt,name=observation,proto3,oneof" json:"observation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transaction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Transaction) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *Transaction) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Transaction) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *Transaction) GetDeletedBy() uint32 {
	if x != nil && x.DeletedBy != nil {
		return *x.DeletedBy
	}
	return 0
}

func (x *Transaction) GetOriginAccountId() uint32 {
	if x != nil {
		return x.OriginAccountId
	}
	return 0
}

func (x *Transaction) GetDestinationAccountId() uint32 {
	if x != nil {
		return x.DestinationAccountId
	}
	return 0
}

func (x *Transaction) GetTransactionTypeId() uint32 {
	if x != nil {
		return x.TransactionTypeId
	}
	return 0
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetExchangeId() uint32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *Transaction) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *Transaction) GetObservation() string {
	if x != nil && x.Observation != nil {
		return *x.Observation
	}
	return ""
}

type CreateTransactionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequesterId          uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	OriginAccountId      uint32                 `protobuf:"varint,2,opt,name=origin_account_id,json=originAccountId,proto3" json:"origin_account_id,omitempty"`
	DestinationAccountId uint32                 `protobuf:"varint,3,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	TransactionTypeId    uint32                 `protobuf:"varint,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ExchangeId           uint32                 `protobuf:"varint,6,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Successful           bool                   `protobuf:"varint,7,opt,name=successful,proto3" json:"successful,omitempty"`
	Observation          *string                `protobuf:"bytes,8,opt,name=observation,proto3,oneof" json:"observation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateTransactionRequest) GetOriginAccountId() uint32 {
	if x != nil {
		return x.OriginAccountId
	}
	return 0
}

func (x *CreateTransactionRequest) GetDestinationAccountId() uint32 {
	if x != nil {
		return x.DestinationAccountId
	}
	return 0
}

func (x *CreateTransactionRequest) GetTransactionTypeId() uint32 {
	if x != nil {
		return x.TransactionTypeId
	}
	return 0
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetExchangeId() uint32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *CreateTransactionRequest) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *CreateTransactionRequest) GetObservation() string {
	if x != nil && x.Observation != nil {
		return *x.Observation
	}
	return ""
}

type CreateTransactionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequesterId          uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	OriginAccountId      uint32                 `protobuf:"varint,2,opt,name=origin_account_id,json=originAccountId,proto3" json:"origin_account_id,omitempty"`
	DestinationAccountId uint32                 `protobuf:"varint,3,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	TransactionTypeId    uint32                 `protobuf:"varint,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ExchangeId           uint32                 `protobuf:"varint,6,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Successful           bool                   `protobuf:"varint,7,opt,name=successful,proto3" json:"successful,omitempty"`
	Observation          string                 `protobuf:"bytes,8,opt,name=observation,proto3" json:"observation,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string                 `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedBy            uint32                 `protobuf:"varint,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            uint32                 `protobuf:"varint,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy            uint32                 `protobuf:"varint,14,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransactionResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateTransactionResponse) GetOriginAccountId() uint32 {
	if x != nil {
		return x.OriginAccountId
	}
	return 0
}

func (x *CreateTransactionResponse) GetDestinationAccountId() uint32 {
	if x != nil {
		return x.DestinationAccountId
	}
	return 0
}

func (x *CreateTransactionResponse) GetTransactionTypeId() uint32 {
	if x != nil {
		return x.TransactionTypeId
	}
	return 0
}

func (x *CreateTransactionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionResponse) GetExchangeId() uint32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *CreateTransactionResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *CreateTransactionResponse) GetObservation() string {
	if x != nil {
		return x.Observation
	}
	return ""
}

func (x *CreateTransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateTransactionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateTransactionResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *CreateTransactionResponse) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *CreateTransactionResponse) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *CreateTransactionResponse) GetDeletedBy() uint32 {
	if x != nil {
		return x.DeletedBy
	}
	return 0
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTransactionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequesterId          uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	OriginAccountId      uint32                 `protobuf:"varint,2,opt,name=origin_account_id,json=originAccountId,proto3" json:"origin_account_id,omitempty"`
	DestinationAccountId uint32                 `protobuf:"varint,3,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	TransactionTypeId    uint32                 `protobuf:"varint,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ExchangeId           uint32                 `protobuf:"varint,6,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Successful           bool                   `protobuf:"varint,7,opt,name=successful,proto3" json:"successful,omitempty"`
	Observation          string                 `protobuf:"bytes,8,opt,name=observation,proto3" json:"observation,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string                 `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedBy            uint32                 `protobuf:"varint,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            uint32                 `protobuf:"varint,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy            uint32                 `protobuf:"varint,14,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GetTransactionResponse) GetOriginAccountId() uint32 {
	if x != nil {
		return x.OriginAccountId
	}
	return 0
}

func (x *GetTransactionResponse) GetDestinationAccountId() uint32 {
	if x != nil {
		return x.DestinationAccountId
	}
	return 0
}

func (x *GetTransactionResponse) GetTransactionTypeId() uint32 {
	if x != nil {
		return x.TransactionTypeId
	}
	return 0
}

func (x *GetTransactionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetTransactionResponse) GetExchangeId() uint32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *GetTransactionResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *GetTransactionResponse) GetObservation() string {
	if x != nil {
		return x.Observation
	}
	return ""
}

func (x *GetTransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetTransactionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetTransactionResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *GetTransactionResponse) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *GetTransactionResponse) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *GetTransactionResponse) GetDeletedBy() uint32 {
	if x != nil {
		return x.DeletedBy
	}
	return 0
}

type UpdateTransactionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId          uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	OriginAccountId      *uint32                `protobuf:"varint,3,opt,name=origin_account_id,json=originAccountId,proto3,oneof" json:"origin_account_id,omitempty"`
	DestinationAccountId *uint32                `protobuf:"varint,4,opt,name=destination_account_id,json=destinationAccountId,proto3,oneof" json:"destination_account_id,omitempty"`
	TransactionTypeId    *uint32                `protobuf:"varint,5,opt,name=transaction_type_id,json=transactionTypeId,proto3,oneof" json:"transaction_type_id,omitempty"`
	Amount               *float64               `protobuf:"fixed64,6,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	ExchangeId           *uint32                `protobuf:"varint,7,opt,name=exchange_id,json=exchangeId,proto3,oneof" json:"exchange_id,omitempty"`
	Successful           *bool                  `protobuf:"varint,8,opt,name=successful,proto3,oneof" json:"successful,omitempty"`
	Observation          *string                `protobuf:"bytes,9,opt,name=observation,proto3,oneof" json:"observation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransactionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTransactionRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetOriginAccountId() uint32 {
	if x != nil && x.OriginAccountId != nil {
		return *x.OriginAccountId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetDestinationAccountId() uint32 {
	if x != nil && x.DestinationAccountId != nil {
		return *x.DestinationAccountId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetTransactionTypeId() uint32 {
	if x != nil && x.TransactionTypeId != nil {
		return *x.TransactionTypeId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetExchangeId() uint32 {
	if x != nil && x.ExchangeId != nil {
		return *x.ExchangeId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetSuccessful() bool {
	if x != nil && x.Successful != nil {
		return *x.Successful
	}
	return false
}

func (x *UpdateTransactionRequest) GetObservation() string {
	if x != nil && x.Observation != nil {
		return *x.Observation
	}
	return ""
}

type UpdateTransactionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequesterId          uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	OriginAccountId      uint32                 `protobuf:"varint,2,opt,name=origin_account_id,json=originAccountId,proto3" json:"origin_account_id,omitempty"`
	DestinationAccountId uint32                 `protobuf:"varint,3,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	TransactionTypeId    uint32                 `protobuf:"varint,4,opt,name=transaction_type_id,json=transactionTypeId,proto3" json:"transaction_type_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	ExchangeId           uint32                 `protobuf:"varint,6,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"`
	Successful           bool                   `protobuf:"varint,7,opt,name=successful,proto3" json:"successful,omitempty"`
	Observation          string                 `protobuf:"bytes,8,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateTransactionResponse) Reset() {
	*x = UpdateTransactionResponse{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionResponse) ProtoMessage() {}

func (x *UpdateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTransactionResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *UpdateTransactionResponse) GetOriginAccountId() uint32 {
	if x != nil {
		return x.OriginAccountId
	}
	return 0
}

func (x *UpdateTransactionResponse) GetDestinationAccountId() uint32 {
	if x != nil {
		return x.DestinationAccountId
	}
	return 0
}

func (x *UpdateTransactionResponse) GetTransactionTypeId() uint32 {
	if x != nil {
		return x.TransactionTypeId
	}
	return 0
}

func (x *UpdateTransactionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionResponse) GetExchangeId() uint32 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *UpdateTransactionResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *UpdateTransactionResponse) GetObservation() string {
	if x != nil {
		return x.Observation
	}
	return ""
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTransactionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteTransactionRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type DeleteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionResponse) Reset() {
	*x = DeleteTransactionResponse{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionResponse) ProtoMessage() {}

func (x *DeleteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTransactionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Limit                *uint32                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset               *uint32                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	IncludeDeleted       *bool                  `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	OriginAccountId      *uint32                `protobuf:"varint,4,opt,name=origin_account_id,json=originAccountId,proto3,oneof" json:"origin_account_id,omitempty"`
	DestinationAccountId *uint32                `protobuf:"varint,5,opt,name=destination_account_id,json=destinationAccountId,proto3,oneof" json:"destination_account_id,omitempty"`
	TransactionTypeId    *uint32                `protobuf:"varint,6,opt,name=transaction_type_id,json=transactionTypeId,proto3,oneof" json:"transaction_type_id,omitempty"`
	Amount               *float64               `protobuf:"fixed64,7,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	ExchangeId           *uint32                `protobuf:"varint,8,opt,name=exchange_id,json=exchangeId,proto3,oneof" json:"exchange_id,omitempty"`
	Successful           *bool                  `protobuf:"varint,9,opt,name=successful,proto3,oneof" json:"successful,omitempty"`
	Observation          *string                `protobuf:"bytes,10,opt,name=observation,proto3,oneof" json:"observation,omitempty"`
	Orderby              *OrderBy               `protobuf:"bytes,11,opt,name=orderby,proto3,oneof" json:"orderby,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListTransactionRequest) Reset() {
	*x = ListTransactionRequest{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionRequest) ProtoMessage() {}

func (x *ListTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *ListTransactionRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListTransactionRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListTransactionRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

func (x *ListTransactionRequest) GetOriginAccountId() uint32 {
	if x != nil && x.OriginAccountId != nil {
		return *x.OriginAccountId
	}
	return 0
}

func (x *ListTransactionRequest) GetDestinationAccountId() uint32 {
	if x != nil && x.DestinationAccountId != nil {
		return *x.DestinationAccountId
	}
	return 0
}

func (x *ListTransactionRequest) GetTransactionTypeId() uint32 {
	if x != nil && x.TransactionTypeId != nil {
		return *x.TransactionTypeId
	}
	return 0
}

func (x *ListTransactionRequest) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *ListTransactionRequest) GetExchangeId() uint32 {
	if x != nil && x.ExchangeId != nil {
		return *x.ExchangeId
	}
	return 0
}

func (x *ListTransactionRequest) GetSuccessful() bool {
	if x != nil && x.Successful != nil {
		return *x.Successful
	}
	return false
}

func (x *ListTransactionRequest) GetObservation() string {
	if x != nil && x.Observation != nil {
		return *x.Observation
	}
	return ""
}

func (x *ListTransactionRequest) GetOrderby() *OrderBy {
	if x != nil {
		return x.Orderby
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *OrderBy) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *OrderBy) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

type ListTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Transaction         `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionResponse) Reset() {
	*x = ListTransactionResponse{}
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionResponse) ProtoMessage() {}

func (x *ListTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_service_protos_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transactions_service_protos_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *ListTransactionResponse) GetRows() []*Transaction {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListTransactionResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_transactions_service_protos_transaction_proto protoreflect.FileDescriptor

const file_transactions_service_protos_transaction_proto_rawDesc = "" +
	"\n" +
	"-transactions_service/protos/transaction.proto\x12\x11transaction_proto\"\xa1\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\tH\x00R\tdeletedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\rR\tupdatedBy\x12\"\n" +
	"\n" +
	"deleted_by\x18\a \x01(\rH\x01R\tdeletedBy\x88\x01\x01\x12*\n" +
	"\x11origin_account_id\x18\b \x01(\rR\x0foriginAccountId\x124\n" +
	"\x16destination_account_id\x18\t \x01(\rR\x14destinationAccountId\x12.\n" +
	"\x13transaction_type_id\x18\n" +
	" \x01(\rR\x11transactionTypeId\x12\x16\n" +
	"\x06amount\x18\v \x01(\x01R\x06amount\x12\x1f\n" +
	"\vexchange_id\x18\f \x01(\rR\n" +
	"exchangeId\x12\x1e\n" +
	"\n" +
	"successful\x18\r \x01(\bR\n" +
	"successful\x12%\n" +
	"\vobservation\x18\x0e \x01(\tH\x02R\vobservation\x88\x01\x01B\r\n" +
	"\v_deleted_atB\r\n" +
	"\v_deleted_byB\x0e\n" +
	"\f_observation\"\xdf\x02\n" +
	"\x18CreateTransactionRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12*\n" +
	"\x11origin_account_id\x18\x02 \x01(\rR\x0foriginAccountId\x124\n" +
	"\x16destination_account_id\x18\x03 \x01(\rR\x14destinationAccountId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\rR\x11transactionTypeId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vexchange_id\x18\x06 \x01(\rR\n" +
	"exchangeId\x12\x1e\n" +
	"\n" +
	"successful\x18\a \x01(\bR\n" +
	"successful\x12%\n" +
	"\vobservation\x18\b \x01(\tH\x00R\vobservation\x88\x01\x01B\x0e\n" +
	"\f_observation\"\x85\x04\n" +
	"\x19CreateTransactionResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12*\n" +
	"\x11origin_account_id\x18\x02 \x01(\rR\x0foriginAccountId\x124\n" +
	"\x16destination_account_id\x18\x03 \x01(\rR\x14destinationAccountId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\rR\x11transactionTypeId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vexchange_id\x18\x06 \x01(\rR\n" +
	"exchangeId\x12\x1e\n" +
	"\n" +
	"successful\x18\a \x01(\bR\n" +
	"successful\x12 \n" +
	"\vobservation\x18\b \x01(\tR\vobservation\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\v \x01(\tR\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\r \x01(\rR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x0e \x01(\rR\tdeletedBy\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x82\x04\n" +
	"\x16GetTransactionResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12*\n" +
	"\x11origin_account_id\x18\x02 \x01(\rR\x0foriginAccountId\x124\n" +
	"\x16destination_account_id\x18\x03 \x01(\rR\x14destinationAccountId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\rR\x11transactionTypeId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vexchange_id\x18\x06 \x01(\rR\n" +
	"exchangeId\x12\x1e\n" +
	"\n" +
	"successful\x18\a \x01(\bR\n" +
	"successful\x12 \n" +
	"\vobservation\x18\b \x01(\tR\vobservation\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\v \x01(\tR\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\r \x01(\rR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x0e \x01(\rR\tdeletedBy\"\x80\x04\n" +
	"\x18UpdateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\x12/\n" +
	"\x11origin_account_id\x18\x03 \x01(\rH\x00R\x0foriginAccountId\x88\x01\x01\x129\n" +
	"\x16destination_account_id\x18\x04 \x01(\rH\x01R\x14destinationAccountId\x88\x01\x01\x123\n" +
	"\x13transaction_type_id\x18\x05 \x01(\rH\x02R\x11transactionTypeId\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x06 \x01(\x01H\x03R\x06amount\x88\x01\x01\x12$\n" +
	"\vexchange_id\x18\a \x01(\rH\x04R\n" +
	"exchangeId\x88\x01\x01\x12#\n" +
	"\n" +
	"successful\x18\b \x01(\bH\x05R\n" +
	"successful\x88\x01\x01\x12%\n" +
	"\vobservation\x18\t \x01(\tH\x06R\vobservation\x88\x01\x01B\x14\n" +
	"\x12_origin_account_idB\x19\n" +
	"\x17_destination_account_idB\x16\n" +
	"\x14_transaction_type_idB\t\n" +
	"\a_amountB\x0e\n" +
	"\f_exchange_idB\r\n" +
	"\v_successfulB\x0e\n" +
	"\f_observation\"\xcb\x02\n" +
	"\x19UpdateTransactionResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12*\n" +
	"\x11origin_account_id\x18\x02 \x01(\rR\x0foriginAccountId\x124\n" +
	"\x16destination_account_id\x18\x03 \x01(\rR\x14destinationAccountId\x12.\n" +
	"\x13transaction_type_id\x18\x04 \x01(\rR\x11transactionTypeId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vexchange_id\x18\x06 \x01(\rR\n" +
	"exchangeId\x12\x1e\n" +
	"\n" +
	"successful\x18\a \x01(\bR\n" +
	"successful\x12 \n" +
	"\vobservation\x18\b \x01(\tR\vobservation\"M\n" +
	"\x18DeleteTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\"5\n" +
	"\x19DeleteTransactionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa1\x05\n" +
	"\x16ListTransactionRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\rH\x01R\x06offset\x88\x01\x01\x12,\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bH\x02R\x0eincludeDeleted\x88\x01\x01\x12/\n" +
	"\x11origin_account_id\x18\x04 \x01(\rH\x03R\x0foriginAccountId\x88\x01\x01\x129\n" +
	"\x16destination_account_id\x18\x05 \x01(\rH\x04R\x14destinationAccountId\x88\x01\x01\x123\n" +
	"\x13transaction_type_id\x18\x06 \x01(\rH\x05R\x11transactionTypeId\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\a \x01(\x01H\x06R\x06amount\x88\x01\x01\x12$\n" +
	"\vexchange_id\x18\b \x01(\rH\aR\n" +
	"exchangeId\x88\x01\x01\x12#\n" +
	"\n" +
	"successful\x18\t \x01(\bH\bR\n" +
	"successful\x88\x01\x01\x12%\n" +
	"\vobservation\x18\n" +
	" \x01(\tH\tR\vobservation\x88\x01\x01\x129\n" +
	"\aorderby\x18\v \x01(\v2\x1a.transaction_proto.OrderByH\n" +
	"R\aorderby\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x12\n" +
	"\x10_include_deletedB\x14\n" +
	"\x12_origin_account_idB\x19\n" +
	"\x17_destination_account_idB\x16\n" +
	"\x14_transaction_type_idB\t\n" +
	"\a_amountB\x0e\n" +
	"\f_exchange_idB\r\n" +
	"\v_successfulB\x0e\n" +
	"\f_observationB\n" +
	"\n" +
	"\b_orderby\"X\n" +
	"\aOrderBy\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tH\x01R\tcreatedAt\x88\x01\x01B\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_at\"c\n" +
	"\x17ListTransactionResponse\x122\n" +
	"\x04rows\x18\x01 \x03(\v2\x1e.transaction_proto.TransactionR\x04rows\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count2\xfe\x03\n" +
	"\x12TransactionService\x12c\n" +
	"\x06Create\x12+.transaction_proto.CreateTransactionRequest\x1a,.transaction_proto.CreateTransactionResponse\x12Z\n" +
	"\x03Get\x12(.transaction_proto.GetTransactionRequest\x1a).transaction_proto.GetTransactionResponse\x12c\n" +
	"\x06Update\x12+.transaction_proto.UpdateTransactionRequest\x1a,.transaction_proto.UpdateTransactionResponse\x12c\n" +
	"\x06Delete\x12+.transaction_proto.DeleteTransactionRequest\x1a,.transaction_proto.DeleteTransactionResponse\x12]\n" +
	"\x04List\x12).transaction_proto.ListTransactionRequest\x1a*.transaction_proto.ListTransactionResponseB&Z$./generated_protos/transaction_protob\x06proto3"

var (
	file_transactions_service_protos_transaction_proto_rawDescOnce sync.Once
	file_transactions_service_protos_transaction_proto_rawDescData []byte
)

func file_transactions_service_protos_transaction_proto_rawDescGZIP() []byte {
	file_transactions_service_protos_transaction_proto_rawDescOnce.Do(func() {
		file_transactions_service_protos_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transactions_service_protos_transaction_proto_rawDesc), len(file_transactions_service_protos_transaction_proto_rawDesc)))
	})
	return file_transactions_service_protos_transaction_proto_rawDescData
}

var file_transactions_service_protos_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transactions_service_protos_transaction_proto_goTypes = []any{
	(*Transaction)(nil),               // 0: transaction_proto.Transaction
	(*CreateTransactionRequest)(nil),  // 1: transaction_proto.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 2: transaction_proto.CreateTransactionResponse
	(*GetTransactionRequest)(nil),     // 3: transaction_proto.GetTransactionRequest
	(*GetTransactionResponse)(nil),    // 4: transaction_proto.GetTransactionResponse
	(*UpdateTransactionRequest)(nil),  // 5: transaction_proto.UpdateTransactionRequest
	(*UpdateTransactionResponse)(nil), // 6: transaction_proto.UpdateTransactionResponse
	(*DeleteTransactionRequest)(nil),  // 7: transaction_proto.DeleteTransactionRequest
	(*DeleteTransactionResponse)(nil), // 8: transaction_proto.DeleteTransactionResponse
	(*ListTransactionRequest)(nil),    // 9: transaction_proto.ListTransactionRequest
	(*OrderBy)(nil),                   // 10: transaction_proto.OrderBy
	(*ListTransactionResponse)(nil),   // 11: transaction_proto.ListTransactionResponse
}
var file_transactions_service_protos_transaction_proto_depIdxs = []int32{
	10, // 0: transaction_proto.ListTransactionRequest.orderby:type_name -> transaction_proto.OrderBy
	0,  // 1: transaction_proto.ListTransactionResponse.rows:type_name -> transaction_proto.Transaction
	1,  // 2: transaction_proto.TransactionService.Create:input_type -> transaction_proto.CreateTransactionRequest
	3,  // 3: transaction_proto.TransactionService.Get:input_type -> transaction_proto.GetTransactionRequest
	5,  // 4: transaction_proto.TransactionService.Update:input_type -> transaction_proto.UpdateTransactionRequest
	7,  // 5: transaction_proto.TransactionService.Delete:input_type -> transaction_proto.DeleteTransactionRequest
	9,  // 6: transaction_proto.TransactionService.List:input_type -> transaction_proto.ListTransactionRequest
	2,  // 7: transaction_proto.TransactionService.Create:output_type -> transaction_proto.CreateTransactionResponse
	4,  // 8: transaction_proto.TransactionService.Get:output_type -> transaction_proto.GetTransactionResponse
	6,  // 9: transaction_proto.TransactionService.Update:output_type -> transaction_proto.UpdateTransactionResponse
	8,  // 10: transaction_proto.TransactionService.Delete:output_type -> transaction_proto.DeleteTransactionResponse
	11, // 11: transaction_proto.TransactionService.List:output_type -> transaction_proto.ListTransactionResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_transactions_service_protos_transaction_proto_init() }
func file_transactions_service_protos_transaction_proto_init() {
	if File_transactions_service_protos_transaction_proto != nil {
		return
	}
	file_transactions_service_protos_transaction_proto_msgTypes[0].OneofWrappers = []any{}
	file_transactions_service_protos_transaction_proto_msgTypes[1].OneofWrappers = []any{}
	file_transactions_service_protos_transaction_proto_msgTypes[5].OneofWrappers = []any{}
	file_transactions_service_protos_transaction_proto_msgTypes[9].OneofWrappers = []any{}
	file_transactions_service_protos_transaction_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transactions_service_protos_transaction_proto_rawDesc), len(file_transactions_service_protos_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transactions_service_protos_transaction_proto_goTypes,
		DependencyIndexes: file_transactions_service_protos_transaction_proto_depIdxs,
		MessageInfos:      file_transactions_service_protos_transaction_proto_msgTypes,
	}.Build()
	File_transactions_service_protos_transaction_proto = out.File
	file_transactions_service_protos_transaction_proto_goTypes = nil
	file_transactions_service_protos_transaction_proto_depIdxs = nil
}
