// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/bank.proto

package bank_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BankNumber    string                 `protobuf:"bytes,3,opt,name=bank_number,json=bankNumber,proto3" json:"bank_number,omitempty"`
	CreatedBy     uint32                 `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     uint32                 `protobuf:"varint,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy     *uint32                `protobuf:"varint,7,opt,name=deleted_by,json=deletedBy,proto3,oneof" json:"deleted_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,11,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank) Reset() {
	*x = Bank{}
	mi := &file_protos_bank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{0}
}

func (x *Bank) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bank) GetBankNumber() string {
	if x != nil {
		return x.BankNumber
	}
	return ""
}

func (x *Bank) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Bank) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *Bank) GetDeletedBy() uint32 {
	if x != nil && x.DeletedBy != nil {
		return *x.DeletedBy
	}
	return 0
}

func (x *Bank) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Bank) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Bank) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

func (x *Bank) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type CreateBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BankNumber    string                 `protobuf:"bytes,3,opt,name=bank_number,json=bankNumber,proto3" json:"bank_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankRequest) Reset() {
	*x = CreateBankRequest{}
	mi := &file_protos_bank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankRequest) ProtoMessage() {}

func (x *CreateBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankRequest.ProtoReflect.Descriptor instead.
func (*CreateBankRequest) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBankRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateBankRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBankRequest) GetBankNumber() string {
	if x != nil {
		return x.BankNumber
	}
	return ""
}

type CreateBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BankNumber    string                 `protobuf:"bytes,3,opt,name=bank_number,json=bankNumber,proto3" json:"bank_number,omitempty"`
	CreatedBy     uint32                 `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     uint32                 `protobuf:"varint,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy     uint32                 `protobuf:"varint,6,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBankResponse) Reset() {
	*x = CreateBankResponse{}
	mi := &file_protos_bank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBankResponse) ProtoMessage() {}

func (x *CreateBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBankResponse.ProtoReflect.Descriptor instead.
func (*CreateBankResponse) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBankResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *CreateBankResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBankResponse) GetBankNumber() string {
	if x != nil {
		return x.BankNumber
	}
	return ""
}

func (x *CreateBankResponse) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *CreateBankResponse) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *CreateBankResponse) GetDeletedBy() uint32 {
	if x != nil {
		return x.DeletedBy
	}
	return 0
}

func (x *CreateBankResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateBankResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CreateBankResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type GetBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankRequest) Reset() {
	*x = GetBankRequest{}
	mi := &file_protos_bank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankRequest) ProtoMessage() {}

func (x *GetBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankRequest.ProtoReflect.Descriptor instead.
func (*GetBankRequest) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{3}
}

func (x *GetBankRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BankNumber    string                 `protobuf:"bytes,3,opt,name=bank_number,json=bankNumber,proto3" json:"bank_number,omitempty"`
	CreatedBy     uint32                 `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     uint32                 `protobuf:"varint,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	DeletedBy     uint32                 `protobuf:"varint,6,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankResponse) Reset() {
	*x = GetBankResponse{}
	mi := &file_protos_bank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankResponse) ProtoMessage() {}

func (x *GetBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankResponse.ProtoReflect.Descriptor instead.
func (*GetBankResponse) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{4}
}

func (x *GetBankResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *GetBankResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBankResponse) GetBankNumber() string {
	if x != nil {
		return x.BankNumber
	}
	return ""
}

func (x *GetBankResponse) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *GetBankResponse) GetUpdatedBy() uint32 {
	if x != nil {
		return x.UpdatedBy
	}
	return 0
}

func (x *GetBankResponse) GetDeletedBy() uint32 {
	if x != nil {
		return x.DeletedBy
	}
	return 0
}

func (x *GetBankResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetBankResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetBankResponse) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type UpdateBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   int32                  `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BankNumber    *string                `protobuf:"bytes,4,opt,name=bank_number,json=bankNumber,proto3,oneof" json:"bank_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBankRequest) Reset() {
	*x = UpdateBankRequest{}
	mi := &file_protos_bank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBankRequest) ProtoMessage() {}

func (x *UpdateBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBankRequest.ProtoReflect.Descriptor instead.
func (*UpdateBankRequest) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBankRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBankRequest) GetRequesterId() int32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *UpdateBankRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateBankRequest) GetBankNumber() string {
	if x != nil && x.BankNumber != nil {
		return *x.BankNumber
	}
	return ""
}

type UpdateBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   uint32                 `protobuf:"varint,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BankNumber    string                 `protobuf:"bytes,3,opt,name=bank_number,json=bankNumber,proto3" json:"bank_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBankResponse) Reset() {
	*x = UpdateBankResponse{}
	mi := &file_protos_bank_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBankResponse) ProtoMessage() {}

func (x *UpdateBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBankResponse.ProtoReflect.Descriptor instead.
func (*UpdateBankResponse) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBankResponse) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

func (x *UpdateBankResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBankResponse) GetBankNumber() string {
	if x != nil {
		return x.BankNumber
	}
	return ""
}

type DeleteBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RequesterId   uint32                 `protobuf:"varint,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBankRequest) Reset() {
	*x = DeleteBankRequest{}
	mi := &file_protos_bank_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBankRequest) ProtoMessage() {}

func (x *DeleteBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBankRequest.ProtoReflect.Descriptor instead.
func (*DeleteBankRequest) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBankRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteBankRequest) GetRequesterId() uint32 {
	if x != nil {
		return x.RequesterId
	}
	return 0
}

type DeleteBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBankResponse) Reset() {
	*x = DeleteBankResponse{}
	mi := &file_protos_bank_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBankResponse) ProtoMessage() {}

func (x *DeleteBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBankResponse.ProtoReflect.Descriptor instead.
func (*DeleteBankResponse) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBankResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListBankRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          *uint32                `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset         *uint32                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	IncludeDeleted *bool                  `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3,oneof" json:"include_deleted,omitempty"`
	Name           *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BankNumber     *string                `protobuf:"bytes,5,opt,name=bank_number,json=bankNumber,proto3,oneof" json:"bank_number,omitempty"`
	Orderby        *OrderBy               `protobuf:"bytes,6,opt,name=orderby,proto3,oneof" json:"orderby,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBankRequest) Reset() {
	*x = ListBankRequest{}
	mi := &file_protos_bank_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBankRequest) ProtoMessage() {}

func (x *ListBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBankRequest.ProtoReflect.Descriptor instead.
func (*ListBankRequest) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{9}
}

func (x *ListBankRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListBankRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListBankRequest) GetIncludeDeleted() bool {
	if x != nil && x.IncludeDeleted != nil {
		return *x.IncludeDeleted
	}
	return false
}

func (x *ListBankRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListBankRequest) GetBankNumber() string {
	if x != nil && x.BankNumber != nil {
		return *x.BankNumber
	}
	return ""
}

func (x *ListBankRequest) GetOrderby() *OrderBy {
	if x != nil {
		return x.Orderby
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Id            *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreatedAt     *string                `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_protos_bank_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{10}
}

func (x *OrderBy) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OrderBy) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *OrderBy) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

type ListBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Bank                `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBankResponse) Reset() {
	*x = ListBankResponse{}
	mi := &file_protos_bank_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBankResponse) ProtoMessage() {}

func (x *ListBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_bank_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBankResponse.ProtoReflect.Descriptor instead.
func (*ListBankResponse) Descriptor() ([]byte, []int) {
	return file_protos_bank_proto_rawDescGZIP(), []int{11}
}

func (x *ListBankResponse) GetRows() []*Bank {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListBankResponse) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_protos_bank_proto protoreflect.FileDescriptor

const file_protos_bank_proto_rawDesc = "" +
	"\n" +
	"\x11protos/bank.proto\x12\n" +
	"bank_proto\"\xd0\x02\n" +
	"\x04Bank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vbank_number\x18\x03 \x01(\tR\n" +
	"bankNumber\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x06 \x01(\rR\tupdatedBy\x12\"\n" +
	"\n" +
	"deleted_by\x18\a \x01(\rH\x00R\tdeletedBy\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\tH\x01R\tdeletedAt\x88\x01\x01\x12!\n" +
	"\frequester_id\x18\v \x01(\rR\vrequesterIdB\r\n" +
	"\v_deleted_byB\r\n" +
	"\v_deleted_at\"k\n" +
	"\x11CreateBankRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vbank_number\x18\x03 \x01(\tR\n" +
	"bankNumber\"\xa6\x02\n" +
	"\x12CreateBankResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vbank_number\x18\x03 \x01(\tR\n" +
	"bankNumber\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\rR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x06 \x01(\rR\tdeletedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\t \x01(\tR\tdeletedAt\" \n" +
	"\x0eGetBankRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xa3\x02\n" +
	"\x0fGetBankResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vbank_number\x18\x03 \x01(\tR\n" +
	"bankNumber\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\rR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\rR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x06 \x01(\rR\tdeletedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\t \x01(\tR\tdeletedAt\"\x9e\x01\n" +
	"\x11UpdateBankRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\x05R\vrequesterId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12$\n" +
	"\vbank_number\x18\x04 \x01(\tH\x01R\n" +
	"bankNumber\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_bank_number\"l\n" +
	"\x12UpdateBankResponse\x12!\n" +
	"\frequester_id\x18\x01 \x01(\rR\vrequesterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vbank_number\x18\x03 \x01(\tR\n" +
	"bankNumber\"F\n" +
	"\x11DeleteBankRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\frequester_id\x18\x02 \x01(\rR\vrequesterId\".\n" +
	"\x12DeleteBankResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb8\x02\n" +
	"\x0fListBankRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\rH\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\rH\x01R\x06offset\x88\x01\x01\x12,\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bH\x02R\x0eincludeDeleted\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x03R\x04name\x88\x01\x01\x12$\n" +
	"\vbank_number\x18\x05 \x01(\tH\x04R\n" +
	"bankNumber\x88\x01\x01\x122\n" +
	"\aorderby\x18\x06 \x01(\v2\x13.bank_proto.OrderByH\x05R\aorderby\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\x12\n" +
	"\x10_include_deletedB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_bank_numberB\n" +
	"\n" +
	"\b_orderby\"z\n" +
	"\aOrderBy\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x01R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tH\x02R\tcreatedAt\x88\x01\x01B\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_idB\r\n" +
	"\v_created_at\"N\n" +
	"\x10ListBankResponse\x12$\n" +
	"\x04rows\x18\x01 \x03(\v2\x10.bank_proto.BankR\x04rows\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count2\xeb\x02\n" +
	"\vBankService\x12G\n" +
	"\x06Create\x12\x1d.bank_proto.CreateBankRequest\x1a\x1e.bank_proto.CreateBankResponse\x12>\n" +
	"\x03Get\x12\x1a.bank_proto.GetBankRequest\x1a\x1b.bank_proto.GetBankResponse\x12G\n" +
	"\x06Update\x12\x1d.bank_proto.UpdateBankRequest\x1a\x1e.bank_proto.UpdateBankResponse\x12G\n" +
	"\x06Delete\x12\x1d.bank_proto.DeleteBankRequest\x1a\x1e.bank_proto.DeleteBankResponse\x12A\n" +
	"\x04List\x12\x1b.bank_proto.ListBankRequest\x1a\x1c.bank_proto.ListBankResponseB\x1fZ\x1d./generated_protos/bank_protob\x06proto3"

var (
	file_protos_bank_proto_rawDescOnce sync.Once
	file_protos_bank_proto_rawDescData []byte
)

func file_protos_bank_proto_rawDescGZIP() []byte {
	file_protos_bank_proto_rawDescOnce.Do(func() {
		file_protos_bank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_bank_proto_rawDesc), len(file_protos_bank_proto_rawDesc)))
	})
	return file_protos_bank_proto_rawDescData
}

var file_protos_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protos_bank_proto_goTypes = []any{
	(*Bank)(nil),               // 0: bank_proto.Bank
	(*CreateBankRequest)(nil),  // 1: bank_proto.CreateBankRequest
	(*CreateBankResponse)(nil), // 2: bank_proto.CreateBankResponse
	(*GetBankRequest)(nil),     // 3: bank_proto.GetBankRequest
	(*GetBankResponse)(nil),    // 4: bank_proto.GetBankResponse
	(*UpdateBankRequest)(nil),  // 5: bank_proto.UpdateBankRequest
	(*UpdateBankResponse)(nil), // 6: bank_proto.UpdateBankResponse
	(*DeleteBankRequest)(nil),  // 7: bank_proto.DeleteBankRequest
	(*DeleteBankResponse)(nil), // 8: bank_proto.DeleteBankResponse
	(*ListBankRequest)(nil),    // 9: bank_proto.ListBankRequest
	(*OrderBy)(nil),            // 10: bank_proto.OrderBy
	(*ListBankResponse)(nil),   // 11: bank_proto.ListBankResponse
}
var file_protos_bank_proto_depIdxs = []int32{
	10, // 0: bank_proto.ListBankRequest.orderby:type_name -> bank_proto.OrderBy
	0,  // 1: bank_proto.ListBankResponse.rows:type_name -> bank_proto.Bank
	1,  // 2: bank_proto.BankService.Create:input_type -> bank_proto.CreateBankRequest
	3,  // 3: bank_proto.BankService.Get:input_type -> bank_proto.GetBankRequest
	5,  // 4: bank_proto.BankService.Update:input_type -> bank_proto.UpdateBankRequest
	7,  // 5: bank_proto.BankService.Delete:input_type -> bank_proto.DeleteBankRequest
	9,  // 6: bank_proto.BankService.List:input_type -> bank_proto.ListBankRequest
	2,  // 7: bank_proto.BankService.Create:output_type -> bank_proto.CreateBankResponse
	4,  // 8: bank_proto.BankService.Get:output_type -> bank_proto.GetBankResponse
	6,  // 9: bank_proto.BankService.Update:output_type -> bank_proto.UpdateBankResponse
	8,  // 10: bank_proto.BankService.Delete:output_type -> bank_proto.DeleteBankResponse
	11, // 11: bank_proto.BankService.List:output_type -> bank_proto.ListBankResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protos_bank_proto_init() }
func file_protos_bank_proto_init() {
	if File_protos_bank_proto != nil {
		return
	}
	file_protos_bank_proto_msgTypes[0].OneofWrappers = []any{}
	file_protos_bank_proto_msgTypes[5].OneofWrappers = []any{}
	file_protos_bank_proto_msgTypes[9].OneofWrappers = []any{}
	file_protos_bank_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_bank_proto_rawDesc), len(file_protos_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_bank_proto_goTypes,
		DependencyIndexes: file_protos_bank_proto_depIdxs,
		MessageInfos:      file_protos_bank_proto_msgTypes,
	}.Build()
	File_protos_bank_proto = out.File
	file_protos_bank_proto_goTypes = nil
	file_protos_bank_proto_depIdxs = nil
}
