syntax = "proto3";

package contact_proto;

option go_package = "./generated_protos/contact_proto";

service ContactService {
    // Contact CRUD
    rpc Create (CreateRequest) returns (CreateResponse) {};
    rpc Get (GetRequest) returns (GetResponse) {};
    rpc Update (UpdateRequest) returns (UpdateResponse) {};
    rpc Delete (DeleteRequest) returns (DeleteResponse) {};
    rpc List (ListRequest) returns (ListResponse) {};
}

message ContactDto {
    int32 id = 1;
    string name = 2;
    string chat_id = 3;
    string client_id = 4;
    string phone_number = 5;
    int32 whatsapp_config_id = 6;
}

message CreateRequest {
    ContactDto contact = 1;
}

message CreateResponse {
    ContactDto contact = 1;
}

message GetRequest {
    int32 id = 1;
}

message GetResponse {
    ContactDto contact = 1;
}

message UpdateRequest {
    ContactDto contact = 1;
}

message UpdateResponse {
    ContactDto contact = 1;
}

message DeleteRequest {
    int32 id = 1;
}

message DeleteResponse {}

message ListRequest {
    int32 limit = 1;
    int32 offset = 2;
}

message ListResponse {
    repeated ContactDto rows = 1;
    int32 count = 2;
}